# BACKTESTING_272 — Téléchargement des données
 
**Univers** : STOXX Europe 600  
**Période téléchargment** : 2015-09-01 --> 2026-02-20 --> pour téléchargement de données et avoir de l'historique pour le calcul des signaux
**Benchmark** : ESTRON Index
**Backtest periode** : 2016-12-31 --> 2026-02-20


## 1. Importation des Libraries <a id='1'></a>

In [ ]:
import sys
print(sys.executable)

import pyarrow
print(pyarrow.__version__)

from pathlib import Path

project_root = Path().resolve().parent          # BACKTESTING_M2272
sys.path.insert(0, str(project_root / "src"))   # ajoute src au PYTHONPATH

from request.request_unique import BloombergHistoricalData
from request.utils import ParquetStockage, ExportData, MonthEndExtractor, BloombergDateFormatter, IndexMembersParquetMerger
from request.request_index_members import IndexMembersDownloader


## 2. Requete historique de l'Indice Univers <a id='1'></a>

**Objectif** : Déterminer les dates de requetes fin de mois (date de rebalancement) des composants du stoxx 600 Europe

### 2a. Requete Benchmark SXXP Index

In [ ]:
# Requete
bloom = BloombergHistoricalData()

df = bloom.get_history(ticker="SXXP Index", field="PX_LAST", start_date="20160901", end_date="20260220", frequency="DAILY")

# Sauvegarde
stockage = ParquetStockage()

stockage.sauvegarder(df, nom_fichier="SXXP Index_PX_LAST",ticker="SXXP Index")

"""
- chemin de stockage : /Users/arthurlenet/Desktop/Backtesting_M2272/data/initial_data
"""

In [ ]:
# Visualisation du fichiers .parquet stocké
stockage = ParquetStockage()

sxxp_index_px_last = stockage.charger("SXXP Index_PX_LAST")

sxxp_index_px_last.tail()

            Date  SXXP Index
2427  2026-02-16      618.52
2428  2026-02-17      621.29
2429  2026-02-18      628.69
2430  2026-02-19      625.33
2431  2026-02-20      630.56

### 2b. Requete Risk free Rate/ Benchmark :  ESTRON Index €STER

In [ ]:
# Requete
bloom = BloombergHistoricalData()

df = bloom.get_history(ticker="ESTRON Index", field="PX_LAST", start_date="20160901", end_date="20260220", frequency="DAILY")

# Sauvegarde
stockage = ParquetStockage()

stockage.sauvegarder(df, nom_fichier="ESTRON Index_PX_LAST", ticker="ESTRON Index")

In [ ]:
# Visualisation du fichier téléchargé
estron_index_px_last = stockage.charger("ESTRON Index_PX_LAST")
estron_index_px_last.tail()

            Date  ESTRON Index
1633  2026-02-16         1.929
1634  2026-02-17         1.931
1635  2026-02-18         1.931
1636  2026-02-19         1.933
1637  2026-02-20         1.932

Verification des données

In [ ]:
# Export
exporter = ExportData(folder_type="verification")
exporter.export_df(sxxp_index_px_last, "sxxp_index_px_last")
exporter.export_df(estron_index_px_last, "estron_index_px_last")

WindowsPath('C:/Users/lenar25/Documents/Backtesting_M2272/data/verification/estron_index_px_last_20260226_173300.xlsx')


## 3. Requete historique des composants de l'Indice Univers <a id='1'></a>

**Objectif** : Déterminer les composants du stoxx 600 Europe à chaque date de rebalancement pour éviter les biais de survivants

### 3a. Identifier les dates de fin de chaque mois

In [ ]:
# Load des données
stockage = ParquetStockage()

sxxp_index_px_last = stockage.charger("SXXP Index_PX_LAST")

sxxp_index_px_last.tail()

            Date  SXXP Index
2427  2026-02-16      618.52
2428  2026-02-17      621.29
2429  2026-02-18      628.69
2430  2026-02-19      625.33
2431  2026-02-20      630.56

In [ ]:
# extraction des dates de fin de mois
extractor = MonthEndExtractor(sxxp_index_px_last)
month_end_dates = extractor.get_month_end_dates()

# Exporter pour stockage
exporter = ExportData(folder_type="initial_data")
exporter.export_df(month_end_dates, "month_end_dates")

# mettre en liste les dates de fin de mois
month_end_dates_list = month_end_dates.to_list()

In [ ]:
# visualisation
month_end_dates_list

[Timestamp('2016-09-30 00:00:00'),
 Timestamp('2016-10-31 00:00:00'),
 Timestamp('2016-11-30 00:00:00'),
 Timestamp('2016-12-30 00:00:00'),
 Timestamp('2017-01-31 00:00:00'),
 Timestamp('2017-02-28 00:00:00'),
 Timestamp('2017-03-31 00:00:00'),
 Timestamp('2017-04-28 00:00:00'),
 Timestamp('2017-05-31 00:00:00'),
 Timestamp('2017-06-30 00:00:00'),
 Timestamp('2017-07-31 00:00:00'),
 Timestamp('2017-08-31 00:00:00'),
 Timestamp('2017-09-29 00:00:00'),
 Timestamp('2017-10-31 00:00:00'),
 Timestamp('2017-11-30 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2018-01-31 00:00:00'),
 Timestamp('2018-02-28 00:00:00'),
 Timestamp('2018-03-29 00:00:00'),
 Timestamp('2018-04-30 00:00:00'),
 Timestamp('2018-05-31 00:00:00'),
 Timestamp('2018-06-29 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-08-31 00:00:00'),
 Timestamp('2018-09-28 00:00:00'),
 Timestamp('2018-10-31 00:00:00'),
 Timestamp('2018-11-30 00:00:00'),
 Timestamp('2018-12-31 00:00:00'),
 Timestamp('2019-01-31 00:00:00'),
 Timestamp('2019-02-28 00:00:00'),
 Timestamp('2019-03-29 00:00:00'),
 Timestamp('2019-04-30 00:00:00'),
 Timestamp('2019-05-31 00:00:00'),
 Timestamp('2019-06-28 00:00:00'),
 Timestamp('2019-07-31 00:00:00'),
 Timestamp('2019-08-30 00:00:00'),
 Timestamp('2019-09-30 00:00:00'),
 Timestamp('2019-10-31 00:00:00'),
 Timestamp('2019-11-29 00:00:00'),
 Timestamp('2019-12-31 00:00:00'),
 Timestamp('2020-01-31 00:00:00'),
 Timestamp('2020-02-28 00:00:00'),
 Timestamp('2020-03-31 00:00:00'),
 Timestamp('2020-04-30 00:00:00'),
 Timestamp('2020-05-29 00:00:00'),
 Timestamp('2020-06-30 00:00:00'),
 Timestamp('2020-07-31 00:00:00'),
 Timestamp('2020-08-31 00:00:00'),
 Timestamp('2020-09-30 00:00:00'),
 Timestamp('2020-10-30 00:00:00'),
 Timestamp('2020-11-30 00:00:00'),
 Timestamp('2020-12-31 00:00:00'),
 Timestamp('2021-01-29 00:00:00'),
 Timestamp('2021-02-26 00:00:00'),
 Timestamp('2021-03-31 00:00:00'),
 Timestamp('2021-04-30 00:00:00'),
 Timestamp('2021-05-31 00:00:00'),
 Timestamp('2021-06-30 00:00:00'),
 Timestamp('2021-07-30 00:00:00'),
 Timestamp('2021-08-31 00:00:00'),
 Timestamp('2021-09-30 00:00:00'),
 Timestamp('2021-10-29 00:00:00'),
 Timestamp('2021-11-30 00:00:00'),
 Timestamp('2021-12-31 00:00:00'),
 Timestamp('2022-01-31 00:00:00'),
 Timestamp('2022-02-28 00:00:00'),
 Timestamp('2022-03-31 00:00:00'),
 Timestamp('2022-04-29 00:00:00'),
 Timestamp('2022-05-31 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-07-29 00:00:00'),
 Timestamp('2022-08-31 00:00:00'),
 Timestamp('2022-09-30 00:00:00'),
 Timestamp('2022-10-31 00:00:00'),
 Timestamp('2022-11-30 00:00:00'),
 Timestamp('2022-12-30 00:00:00'),
 Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-02-28 00:00:00'),
 Timestamp('2023-03-31 00:00:00'),
 Timestamp('2023-04-28 00:00:00'),
 Timestamp('2023-05-31 00:00:00'),
 Timestamp('2023-06-30 00:00:00'),
 Timestamp('2023-07-31 00:00:00'),
 Timestamp('2023-08-31 00:00:00'),
 Timestamp('2023-09-29 00:00:00'),
 Timestamp('2023-10-31 00:00:00'),
 Timestamp('2023-11-30 00:00:00'),
 Timestamp('2023-12-29 00:00:00'),
 Timestamp('2024-01-31 00:00:00'),
 Timestamp('2024-02-29 00:00:00'),
 Timestamp('2024-03-28 00:00:00'),
 Timestamp('2024-04-30 00:00:00'),
 Timestamp('2024-05-31 00:00:00'),
 Timestamp('2024-06-28 00:00:00'),
 Timestamp('2024-07-31 00:00:00'),
 Timestamp('2024-08-30 00:00:00'),
 Timestamp('2024-09-30 00:00:00'),
 Timestamp('2024-10-31 00:00:00'),
 Timestamp('2024-11-29 00:00:00'),
 Timestamp('2024-12-31 00:00:00'),
 Timestamp('2025-01-31 00:00:00'),
 Timestamp('2025-02-28 00:00:00'),
 Timestamp('2025-03-31 00:00:00'),
 Timestamp('2025-04-30 00:00:00'),
 Timestamp('2025-05-30 00:00:00'),
 Timestamp('2025-06-30 00:00:00'),
 Timestamp('2025-07-31 00:00:00'),
 Timestamp('2025-08-29 00:00:00'),
 Timestamp('2025-09-30 00:00:00'),
 Timestamp('2025-10-31 00:00:00'),
 Timestamp('2025-11-28 00:00:00'),
 Timestamp('2025-12-31 00:00:00'),
 Timestamp('2026-01-30 00:00:00'),
 Timestamp('2026-02-20 00:00:00')]

In [ ]:
# Reformatter les dates dans le format Bloomberg pour le téléchargments bloomberg des composants
formatter = BloombergDateFormatter(month_end_dates_list)

bloomberg_month_end_dates_list = formatter.to_yyyymmdd()

bloomberg_month_end_dates_list

[20160930,
 20161031,
 20161130,
 20161230,
 20170131,
 20170228,
 20170331,
 20170428,
 20170531,
 20170630,
 20170731,
 20170831,
 20170929,
 20171031,
 20171130,
 20171229,
 20180131,
 20180228,
 20180329,
 20180430,
 20180531,
 20180629,
 20180731,
 20180831,
 20180928,
 20181031,
 20181130,
 20181231,
 20190131,
 20190228,
 20190329,
 20190430,
 20190531,
 20190628,
 20190731,
 20190830,
 20190930,
 20191031,
 20191129,
 20191231,
 20200131,
 20200228,
 20200331,
 20200430,
 20200529,
 20200630,
 20200731,
 20200831,
 20200930,
 20201030,
 20201130,
 20201231,
 20210129,
 20210226,
 20210331,
 20210430,
 20210531,
 20210630,
 20210730,
 20210831,
 20210930,
 20211029,
 20211130,
 20211231,
 20220131,
 20220228,
 20220331,
 20220429,
 20220531,
 20220630,
 20220729,
 20220831,
 20220930,
 20221031,
 20221130,
 20221230,
 20230131,
 20230228,
 20230331,
 20230428,
 20230531,
 20230630,
 20230731,
 20230831,
 20230929,
 20231031,
 20231130,
 20231229,
 20240131,
 20240229,
 20240328,
 20240430,
 20240531,
 20240628,
 20240731,
 20240830,
 20240930,
 20241031,
 20241129,
 20241231,
 20250131,
 20250228,
 20250331,
 20250430,
 20250530,
 20250630,
 20250731,
 20250829,
 20250930,
 20251031,
 20251128,
 20251231,
 20260130,
 20260220]

### 3b. Téléchargement des composants historiques de l'Indice Univers à chaque date de fin de mois

In [ ]:
downloader = IndexMembersDownloader()

downloader.download_members(index_ticker="SXXP Index",dates=bloomberg_month_end_dates_list)

Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20160930.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20161031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20161130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20161230.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170228.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170331.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170428.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170531.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170630.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170731.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170831.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20170929.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20171031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20171130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20171229.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180228.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180329.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180430.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180531.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180629.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180731.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180831.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20180928.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20181031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20181130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20181231.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190228.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190329.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190430.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190531.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190628.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190731.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190830.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20190930.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20191031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20191129.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20191231.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200228.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200331.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200430.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200529.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200630.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200731.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200831.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20200930.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20201030.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20201130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20201231.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210129.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210226.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210331.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210430.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210531.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210630.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210730.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210831.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20210930.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20211029.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20211130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20211231.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220228.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220331.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220429.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220531.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220630.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220729.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220831.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20220930.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20221031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20221130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20221230.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230228.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230331.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230428.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230531.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230630.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230731.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230831.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20230929.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20231031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20231130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20231229.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240229.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240328.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240430.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240531.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240628.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240731.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240830.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20240930.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20241031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20241129.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20241231.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250131.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250228.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250331.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250430.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250530.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250630.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250731.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250829.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20250930.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20251031.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20251128.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20251231.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20260130.parquet
Sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\index_memb_20260220.parquet

In [ ]:
# Test Visualisation
stockage = ParquetStockage()

index_memb_20260220 = stockage.charger("index_memb_20260220")

index_memb_20260220.tail()

           Date   Ticker
595  1970-01-01   YAR NO
596  1970-01-01   ZAL GY
597  1970-01-01  ZEAL DC
598  1970-01-01   ZEG LN
599  1970-01-01  ZURN SE

### 3c. Rassembler l'ensemble des composants historiques dans un seul fichier

In [17]:
merger = IndexMembersParquetMerger()
path_saved = merger.merge_to_parquet()

[INFO] Project root détecté : C:\Users\lenar25\Documents\Backtesting_M2272
[INFO] Dossier cible        : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data
[INFO] Sortie attendue : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\historical_index_memb.parquet
[INFO] 114 fichiers fusionnés
[INFO] Shape final : (68402, 2)
[SUCCESS] Fichier créé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\historical_index_memb.parquet (0.03 MB)

### 3d. Identifier les tickers des composants historiques

In [ ]:
# Load des données
stockage = ParquetStockage()

historical_index_memb = stockage.charger("historical_index_memb")

historical_index_memb.tail()

             Date   Ticker
68397  1970-01-01   YAR NO
68398  1970-01-01   ZAL GY
68399  1970-01-01  ZEAL DC
68400  1970-01-01   ZEG LN
68401  1970-01-01  ZURN SE

In [ ]:
# Anlayse
# taille de la liste
len(historical_index_memb["Ticker"])

# mettre en liste les tickers uniques historique de l'indice stoxx 600 Europe
ticker_list_historical_index_memb_unique = historical_index_memb["Ticker"].unique().tolist()

len(ticker_list_historical_index_memb_unique)

980

In [6]:
ticker_list_historical_index_memb_unique

['1844030D NA',
 '1986986D LN',
 '1CNHI IM',
 '1COV GY',
 '2462936D LN',
 '2578464D GY',
 '2627525D LN',
 'A2A IM',
 'AA/ LN',
 'AAL LN',
 'AALB NA',
 'ABBN SW',
 'ABDN LN',
 'ABE SQ',
 'ABF LN',
 'ABI BB',
 'ABN NA',
 'AC FP',
 'ACA FP',
 'ACKB BB',
 'ACS SQ',
 'AD NA',
 'ADEN SW',
 'ADM LN',
 'ADN LN',
 'ADP FP',
 'ADS GY',
 'AENA SQ',
 'AF FP',
 'AGK LN',
 'AGN NA',
 'AGS BB',
 'AHT LN',
 'AI FP',
 'AIR FP',
 'AKE FP',
 'AKZA NA',
 'ALFA SS',
 'ALO FP',
 'ALSYDB DC',
 'ALV GY',
 'AM FP',
 'AMEAS FH',
 'AMFW LN',
 'AMS SE',
 'AMS SQ',
 'ANDR AV',
 'ANTO LN',
 'ARLN GY',
 'ARYN SW',
 'ASM NA',
 'ASML NA',
 'ASSAB SS',
 'ATC NA',
 'ATCOA SS',
 'ATK LN',
 'ATL IM',
 'ATLN SW',
 'ATO FP',
 'AUTO LN',
 'AV/ LN',
 'AVOL SW',
 'AZM IM',
 'AZN LN',
 'BA/ LN',
 'BAB LN',
 'BAER SW',
 'BALDB SS',
 'BALN SW',
 'BARC LN',
 'BARN SE',
 'BAS GY',
 'BATS LN',
 'BAYN GY',
 'BB FP',
 'BBVA SQ',
 'BBY LN',
 'BEI GY',
 'BEZ LN',
 'BILL SS',
 'BION SE',
 'BIRG ID',
 'BKG LN',
 'BKIA SQ',
 'BKT SQ',
 'BLND LN',
 'BME LN',
 'BME SQ',
 'BMW GY',
 'BN FP',
 'BNP FP',
 'BNR GY',
 'BNZL LN',
 'BOK LN',
 'BOKA NA',
 'BOL FP',
 'BOL SS',
 'BOSS GY',
 'BP IM',
 'BP/ LN',
 'BPE IM',
 'BPOST BB',
 'BRBY LN',
 'BRSN LN',
 'BT/A LN',
 'BTRW LN',
 'BVI FP',
 'BVIC LN',
 'BWY LN',
 'CA FP',
 'CABK SQ',
 'CAP FP',
 'CARLB DC',
 'CAST SS',
 'CBG LN',
 'CBK GY',
 'CCH LN',
 'CCL LN',
 'CDI FP',
 'CEC GY',
 'CEY LN',
 'CEZ CK',
 'CFR SW',
 'CHR DC',
 'CLLN LN',
 'CLN SW',
 'CLNX SQ',
 'CNA LN',
 'CNP FP',
 'CO FP',
 'COB LN',
 'COFB BB',
 'COLOB DC',
 'COLR BB',
 'CON GY',
 'COV FP',
 'CPG LN',
 'CPI AV',
 'CPI LN',
 'CPR IM',
 'CRDA LN',
 'CRH ID',
 'CS FP',
 'CSGN SW',
 'CURY LN',
 'DANSKE DC',
 'DB11 GY',
 'DBK GY',
 'DCC LN',
 'DEC FP',
 'DEMANT DC',
 'DEQ GY',
 'DG FP',
 'DGE LN',
 'DHL GY',
 'DIA SQ',
 'DKSH SE',
 'DLG GY',
 'DLG LN',
 'DLN LN',
 'DMGT LN',
 'DNB NO',
 'DOKA SE',
 'DOM LN',
 'DRX LN',
 'DSM NA',
 'DSV DC',
 'DSY FP',
 'DTE GY',
 'DUE GY',
 'DWNI GY',
 'EBS AV',
 'EDEN FP',
 'EDF FP',
 'EDP PL',
 'EKTAB SS',
 'EL FP',
 'ELE SQ',
 'ELIOR FP',
 'ELISA FH',
 'ELUXB SS',
 'EMEIS FP',
 'EMG LN',
 'EMSN SE',
 'EN FP',
 'ENEL IM',
 'ENG SQ',
 'ENGI FP',
 'ENI IM',
 'ENT LN',
 'ENX FP',
 'EOAN GY',
 'EQNR NO',
 'ERF FP',
 'ERICB SS',
 'ESNT LN',
 'ETL FP',
 'EVK GY',
 'EXO IM',
 'EXPN LN',
 'EZJ LN',
 'FABG SS',
 'FER SQ',
 'FGP LN',
 'FGR FP',
 'FHZN SE',
 'FINGB SS',
 'FLTR ID',
 'FME GY',
 'FNTN GY',
 'FORTUM FH',
 'FPE3 GY',
 'FR FP',
 'FRA GY',
 'FRE GY',
 'FRES LN',
 'FRVIA FP',
 'G IM',
 'G1A GY',
 'GALP PL',
 'GAM SE',
 'GBF GY',
 'GBLB BB',
 'GEBN SW',
 'GET FP',
 'GETIB SS',
 'GF SE',
 'GFC FP',
 'GFS LN',
 'GFTU LN',
 'GIVN SW',
 'GJF NO',
 'GKN LN',
 'GLB ID',
 'GLE FP',
 'GLEN LN',
 'GMAB DC',
 'GN DC',
 'GNK LN',
 'GPE LN',
 'GRF SQ',
 'GSK LN',
 'GTO NA',
 'GXI GY',
 'HAS LN',
 'HBAN SE',
 'HEI GY',
 'HEIA NA',
 'HEIO NA',
 'HEN3 GY',
 'HEXAB SS',
 'HGG LN',
 'HIK LN',
 'HL/ LN',
 'HLMA LN',
 'HLUNB DC',
 'HMB SS',
 'HMSO LN',
 'HNR1 GY',
 'HO FP',
 'HOLN SW',
 'HOT GY',
 'HPOLB SS',
 'HSBA LN',
 'HSX LN',
 'HUH1V FH',
 'HUSQB SS',
 'HWDN LN',
 'IAG LN',
 'IAP LN',
 'IBE SQ',
 'ICA SS',
 'ICAD FP',
 'ICG LN',
 'IDS LN',
 'IFX GY',
 'IGG LN',
 'IHG LN',
 'III LN',
 'ILD FP',
 'IMB LN',
 'IMCD NA',
 'IMI LN',
 'INCH LN',
 'INDUA SS',
 'INDV LN',
 'INF LN',
 'ING FP',
 'INGA NA',
 'INTRUM SS',
 'INTU LN',
 'INVEB SS',
 'INVP LN',
 'IPN FP',
 'ISAT LN',
 'ISP IM',
 'ISS DC',
 'IT IM',
 'ITRK LN',
 'ITV LN',
 'ITX SQ',
 'JE/ LN',
 'JM SS',
 'JMAT LN',
 'JMT PL',
 'JUP LN',
 'JYSK DC',
 'KBC BB',
 'KER FP',
 'KESKOB FH',
 'KGF LN',
 'KGX GY',
 'KINDSDB SS',
 'KINVB SS',
 'KN FP',
 'KNEBV FH',
 'KNIN SW',
 'KOMB CK',
 'KPN NA',
 'KSP ID',
 'KYGA ID',
 'LAND LN',
 'LDO IM',
 'LEG GY',
 'LGEN LN',
 'LHA GY',
 'LI FP',
 'LISN SW',
 'LLOY LN',
 'LNA GY',
 'LOGN SW',
 'LONN SW',
 'LR FP',
 'LSEG LN',
 'LUNDB SS',
 'LUX IM',
 'LXS GY',
 'MAERSKB DC',
 'MAN GY',
 'MAP SQ',
 'MB IM',
 'MBG GY',
 'MC FP',
 'MCRO LN',
 'MDC LN',
 'MERL LN',
 'MF FP',
 'MFEB IM',
 'MGGT LN',
 'MKS LN',
 'ML FP',
 'MMB FP',
 'MNDI LN',
 'MONC IM',
 'MONY LN',
 'MOWI NO',
 'MRK GY',
 'MRL SQ',
 'MRW LN',
 'MT NA',
 'MTX GY',
 'MUV2 GY',
 'NCCB SS',
 'NDA SS',
 'NELES FH',
 'NESN SW',
 'NESTE FH',
 'NG/ LN',
 'NHY NO',
 'NIBEB SS',
 'NK FP',
 'NN NA',
 'NOKIA FH',
 'NOVN SW',
 'NOVOB DC',
 'NSISB DC',
 'NTGY SQ',
 'NWG LN',
 'NXT LN',
 'O2D GY',
 'OCDO LN',
 'OCI NA',
 'OERL SE',
 'OML LN',
 'OMV AV',
 'ONTEX BB',
 'OPM FP',
 'OR FP',
 'ORA FP',
 'ORK NO',
 'ORNBV FH',
 'ORRON SS',
 'ORSTED DC',
 'OSR GY',
 'PAGE LN',
 'PAH3 GY',
 'PARG SE',
 'PAYS LN',
 'PFC LN',
 'PGHN SW',
 'PHIA NA',
 'PHNX LN',
 'PMI IM',
 'PNDORA DC',
 'PNL NA',
 'PNN LN',
 'POLY LN',
 'POP SQ',
 'PROX BB',
 'PRU LN',
 'PRY IM',
 'PSM GY',
 'PSN LN',
 'PSON LN',
 'PSPN SE',
 'PST IM',
 'PTEC LN',
 'PUB FP',
 'QIA GY',
 'QQ/ LN',
 'RACE IM',
 'RAND NA',
 'RBI AV',
 'RDSA NA',
 'REC IM',
 'RED SQ',
 'REL LN',
 'RENT NA',
 'REP SQ',
 'RF FP',
 'RGU LN',
 'RHM GY',
 'RI FP',
 'RIO LN',
 'RKT LN',
 'RMS FP',
 'RMV LN',
 'RNO FP',
 'ROG SW',
 'ROR LN',
 'RPC LN',
 'RR/ LN',
 'RRS LN',
 'RRTL GY',
 'RSA LN',
 'RTO LN',
 'RUI FP',
 'RWE GY',
 'RXL FP',
 'RYA ID',
 'SAABB SS',
 'SAB LN',
 'SAB SQ',
 'SAF FP',
 'SAGA LN',
 'SAMPO FH',
 'SAN FP',
 'SAN SQ',
 'SAND SS',
 'SAP GY',
 'SAZ GY',
 'SBMO NA',
 'SBRY LN',
 'SCAB SS',
 'SCHP SW',
 'SCMN SW',
 'SCR FP',
 'SDF GY',
 'SDR LN',
 'SEBA SS',
 'SECUB SS',
 'SESG FP',
 'SEV FP',
 'SFR FP',
 'SGE LN',
 'SGO FP',
 'SGRE SQ',
 'SGRO LN',
 'SGSN SW',
 'SHB LN',
 'SHBA SS',
 'SHC LN',
 'SHP LN',
 'SIE GY',
 'SIG LN',
 'SIKA SW',
 'SK FP',
 'SKAB SS',
 'SKFB SS',
 'SKG ID',
 'SKY LN',
 'SLHN SW',
 'SMDS LN',
 'SMIN LN',
 'SMWH LN',
 'SN/ LN',
 'SNH GY',
 'SOBI SS',
 'SOLB BB',
 'SOON SW',
 'SPM IM',
 'SPR GY',
 'SPSN SE',
 'SPX LN',
 'SRCG SE',
 'SREN SW',
 'SRG IM',
 'SRT3 GY',
 'SSE LN',
 'STAN LN',
 'STERV FH',
 'STJ LN',
 'STLAM IM',
 'STMMI IM',
 'STMN SE',
 'SU FP',
 'SUBC NO',
 'SVT LN',
 'SW FP',
 'SWEDA SS',
 'SWMA SS',
 'SXS LN',
 'SY1 GY',
 'SYNN SW',
 'TALK LN',
 'TATE LN',
 'TDC DC',
 'TEC FP',
 'TEF SQ',
 'TEL NO',
 'TEL2B SS',
 'TELIA SS',
 'TEMN SE',
 'TEN IM',
 'TEP FP',
 'TIT IM',
 'TKA GY',
 'TL5 SQ',
 'TLW LN',
 'TNET BB',
 'TOP DC',
 'TPK LN',
 'TRELB SS',
 'TRN IM',
 'TRYG DC',
 'TSCO LN',
 'TTE FP',
 'TUI LN',
 'TW/ LN',
 'TYRES FH',
 'UBI FP',
 'UBI IM',
 'UBM LN',
 'UBSG SW',
 'UCB BB',
 'UCG IM',
 'UG FP',
 'UHR SW',
 'UL NA',
 'ULE LN',
 'ULVR LN',
 'UMI BB',
 'UN0 GY',
 'UPM FH',
 'US IM',
 'UTDI GY',
 'UU/ LN',
 'VANQ LN',
 'VANTI FP',
 'VCT LN',
 'VENDA NO',
 'VIE FP',
 'VIFN SW',
 'VIS SQ',
 'VIV FP',
 'VMUK LN',
 'VNA GY',
 'VOD LN',
 'VOE AV',
 'VOLVB SS',
 'VOW3 GY',
 'VPK NA',
 'VTY LN',
 'VWS DC',
 'WDI GY',
 'WEIR LN',
 'WG/ LN',
 'WHA NA',
 'WIE AV',
 'WKL NA',
 'WMH LN',
 'WPG LN',
 'WPP LN',
 'WRT1V FH',
 'WTB LN',
 'YAR NO',
 'ZAL GY',
 'ZC FP',
 'ZOT SQ',
 'ZURN SW',
 'MRO LN',
 'SOW GY',
 'IG IM',
 'BWO AV',
 'CMBN SE',
 'DL NA',
 'GLPG NA',
 'IGY GY',
 'IWG LN',
 'NETS DC',
 'NXG LN',
 'SIM DC',
 'STB NO',
 'BAMI IM',
 'FTI FP',
 'OUT1V FH',
 '2261689D LN',
 'FBK IM',
 'G24 GY',
 'LCL LN',
 'RS1 LN',
 'SSPG LN',
 'TCAP LN',
 'TGS NO',
 'AMUN FP',
 'DB1 GY',
 'ATLN SE',
 'CTEC LN',
 'LIGHT NA',
 'BIM FP',
 'ESSITYB SS',
 'LOOMIS SS',
 'SOP FP',
 'B4B GY',
 'UDG LN',
 '1U1 GY',
 'AIBG ID',
 'ASRNL NA',
 'LISN SE',
 'NDA GY',
 'SPIE FP',
 'ABBN SE',
 'ADEN SE',
 'ARYN SE',
 'AT1 GY',
 'AVOL SE',
 'BAER SE',
 'BALN SE',
 'CFR SE',
 'CLN SE',
 'CSGN SE',
 'ELIS FP',
 'GEBN SE',
 'GIVN SE',
 'HOLN SE',
 'KNIN SE',
 'LOGN SE',
 'LONN SE',
 'NESN SE',
 'NOVN SE',
 'PGHN SE',
 'ROG SE',
 'SCHP SE',
 'SCMN SE',
 'SGSN SE',
 'SIKA SE',
 'SLHN SE',
 'SOON SE',
 'SREN SE',
 'UBSG SE',
 'UHR SE',
 'VIFN SE',
 'ZURN SE',
 'ALT FP',
 'BESI NA',
 'DHER GY',
 'HSV LN',
 'KCR FH',
 'LINU GY',
 'NMC LN',
 'PIRC IM',
 'RCO FP',
 'VACN SE',
 'WAF GY',
 'WCH GY',
 'ABLX BB',
 'AKRBP NO',
 'AMBUB DC',
 'BCP PL',
 'BUCN SE',
 'COL SQ',
 'DOM SS',
 'DPH LN',
 'GLJ GY',
 'HLE GY',
 'AVV LN',
 'ARGX BB',
 'ATE FP',
 'CINE LN',
 'EPIA SS',
 'EVR LN',
 'FLS DC',
 'KAZ LN',
 'MOR GY',
 'OMU LN',
 'QLT LN',
 'RBREW DC',
 'ROCKB DC',
 'SHL GY',
 'TECN SE',
 'TEG GY',
 'URW NA',
 'AAK SS',
 'ADYEN NA',
 'AFX GY',
 'BBOX LN',
 'BC8 GY',
 'CDR PW',
 'DIA IM',
 'DIM FP',
 'EVT GY',
 'GALE SE',
 'KGH PW',
 'LPP PW',
 'NEM GY',
 'PEO PW',
 'PKN PW',
 'PKO PW',
 'PUM GY',
 'PZU PW',
 'SOF BB',
 'SPL PW',
 'UTG LN',
 'VALMT FH',
 'JLT LN',
 'LIN GY',
 'VER AV',
 'IP IM',
 'KBX GY',
 'PGN PW',
 'SALM NO',
 'TOM NO',
 'HER IM',
 'TKWY NA',
 'ALC SE',
 'WDP BB',
 'WLN FP',
 'AMP IM',
 'ASHM LN',
 'BEAN SE',
 'GRG LN',
 'GYC GY',
 'INDT SS',
 'JD/ LN',
 'UNAT NA',
 'AED BB',
 'ALLN SE',
 'AOX GY',
 'ELI BB',
 'EVD GY',
 'NEXI IM',
 'MNG LN',
 'PRX NA',
 'KOJAMO FH',
 'AVST LN',
 'EQT SS',
 'EVO SS',
 'HFG GY',
 'HOLMB SS',
 'NETW LN',
 'SIGN SE',
 'BAKKA NO',
 'DPLM LN',
 'ANA SQ',
 'BG AV',
 'CSP LN',
 'ENTRA NO',
 'FDJU FP',
 'GAW LN',
 'GNS LN',
 'RAA GY',
 'RDW LN',
 'SBBB SS',
 'TMV GY',
 'TRN LN',
 'WIHL SS',
 'ADDTB SS',
 'ADE NO',
 'AGR LN',
 'AXFO SS',
 'BCVN SE',
 'COK GY',
 'CWK LN',
 'GRI LN',
 'IDIA SE',
 'LATOB SS',
 'LIFCOB SS',
 'NETC DC',
 'PHP LN',
 'SINCH SS',
 'SWECB SS',
 'THULE SS',
 'WALLB SS',
 'METSO FH',
 'ADJ GY',
 'AFRY SS',
 'BEIJB SS',
 'CRBN NA',
 'DNP PW',
 'ENR GY',
 'INW IM',
 'JDEP NA',
 'LMP LN',
 'MAS SQ',
 'NEL NO',
 'SOI FP',
 'SRAIL SE',
 'SWON SE',
 'VAR1 GY',
 'DOCM SE',
 'EDPR PL',
 'SFZN SE',
 'ALE PW',
 'SAGAB SS',
 'SCATC NO',
 'THG LN',
 'VPLAYB SS',
 'AZA SS',
 'INPST NA',
 'NOD NO',
 'RDC GY',
 'WIZZ LN',
 'SCT LN',
 'AG1 GY',
 'ALLFG NA',
 'DOCS LN',
 'FDR SQ',
 'FUTR LN',
 'REY IM',
 'ROO LN',
 'SFOR LN',
 'TIGO SS',
 'ALIFB SS',
 'BANB SE',
 'ARCAD NA',
 'BPT LN',
 'BYG LN',
 'NDA FH',
 'QTCOM FH',
 'UMG NA',
 'VITR SS',
 'WISE LN',
 'DARK LN',
 'ZO1 GY',
 'ALKB DC',
 'AUTO NO',
 'DIE BB',
 'DTG GY',
 'INRN SE',
 'MIPS SS',
 'ONT LN',
 'RILBA DC',
 'SAFE LN',
 'SECTB SS',
 'STORB SS',
 'VOLCARB SS',
 'WOSG LN',
 'IVG IM',
 'SHELL NA',
 'KOG NO',
 'OSB LN',
 'SSABB SS',
 'VTWR GY',
 'AIXA GY',
 'FNOX SS',
 'GTT FP',
 'HBR LN',
 'NEX FP',
 'SAVE SS',
 'HLN LN',
 'ALLEI SS',
 'ALFEN NA',
 'ANE SQ',
 'BAVA DC',
 'BKW SE',
 'CCC LN',
 'ECV GY',
 'EXO NA',
 'INDUC SS',
 'LISP SE',
 'LOTB BB',
 'LXI LN',
 'SRP LN',
 'TIETO FH',
 'ENOG LN',
 'HTRO SS',
 'P911 GY',
 'TLX GY',
 'VRLA FP',
 'BC IM',
 'CMBT BB',
 'EMBRACB SS',
 'FRO NO',
 'TE FP',
 'VID SQ',
 'DSFIR NA',
 'DWL LN',
 'URW FP',
 'AZE BB',
 'LAGRB SS',
 'NKT DC',
 'SFSN SE',
 'ACLN SE',
 'BZU IM',
 'CRH LN',
 'SDZ SE',
 'BMPS IM',
 'FLTR LN',
 'SQN SE',
 'SYENS BB',
 'VK FP',
 'ZEAL DC',
 'BBVA SM',
 'BPSO IM',
 'COTN SE',
 'HEM SS',
 'HIAB FH',
 'IBE SM',
 'IFCN SE',
 'IPS FP',
 'ITX SM',
 'SAN SM',
 'UNI IM',
 'SVITZR DC',
 'FUR NA',
 'GALD SE',
 'KEMIRA FH',
 'MTRS SS',
 'MYCR SS',
 'NEOEN FP',
 'TUI1 GY',
 'VAR NO',
 'BMED IM',
 'CVC NA',
 'PUIG SQ',
 'TUB BB',
 'SUN SE',
 'BGN IM',
 'CAN LN',
 'SB1NO NO',
 'VZN SE',
 'PLUS LN',
 'HAG GY',
 'MANTA FH',
 'SUNN SE',
 'TBCG LN',
 'R3NK GY',
 'AMRZ SE',
 'AYV FP',
 'BGEO LN',
 'IDR SQ',
 'LTMC IM',
 'MBK PW',
 'MOBN SE',
 'KBCA BB',
 'ABVX FP',
 'AMV0 GY',
 'CAMX SS',
 'FTK GY',
 'NDX1 GY',
 'UNI SQ',
 'ZEG LN',
 'AAF LN',
 'ACP PW',
 'DLG IM',
 'HUBN SE',
 'MICC NA',
 'MTO LN',
 'VEND NO',
 'VSURE SS']

In [27]:
# stockage
# Export
import pandas as pd
exporter = ExportData(folder_type="verification")
ticker_list_historical_index_memb_unique_dataframe = pd.DataFrame(ticker_list_historical_index_memb_unique)
exporter.export_df(ticker_list_historical_index_memb_unique_dataframe, "ticker_list_historical_index_memb_unique")

WindowsPath('C:/Users/lenar25/Documents/Backtesting_M2272/data/verification/ticker_list_historical_index_memb_unique_20260226_192753.xlsx')

In [ ]:
# reformatage des tickers pour coller avec le format ticker souhiaté par bloomberg
tickers_equity = [t.strip() if "Equity" in t else t.strip() + " Equity" for t in ticker_list_historical_index_memb_unique]

tickers_equity

['1844030D NA Equity',
 '1986986D LN Equity',
 '1CNHI IM Equity',
 '1COV GY Equity',
 '2462936D LN Equity',
 '2578464D GY Equity',
 '2627525D LN Equity',
 'A2A IM Equity',
 'AA/ LN Equity',
 'AAL LN Equity',
 'AALB NA Equity',
 'ABBN SW Equity',
 'ABDN LN Equity',
 'ABE SQ Equity',
 'ABF LN Equity',
 'ABI BB Equity',
 'ABN NA Equity',
 'AC FP Equity',
 'ACA FP Equity',
 'ACKB BB Equity',
 'ACS SQ Equity',
 'AD NA Equity',
 'ADEN SW Equity',
 'ADM LN Equity',
 'ADN LN Equity',
 'ADP FP Equity',
 'ADS GY Equity',
 'AENA SQ Equity',
 'AF FP Equity',
 'AGK LN Equity',
 'AGN NA Equity',
 'AGS BB Equity',
 'AHT LN Equity',
 'AI FP Equity',
 'AIR FP Equity',
 'AKE FP Equity',
 'AKZA NA Equity',
 'ALFA SS Equity',
 'ALO FP Equity',
 'ALSYDB DC Equity',
 'ALV GY Equity',
 'AM FP Equity',
 'AMEAS FH Equity',
 'AMFW LN Equity',
 'AMS SE Equity',
 'AMS SQ Equity',
 'ANDR AV Equity',
 'ANTO LN Equity',
 'ARLN GY Equity',
 'ARYN SW Equity',
 'ASM NA Equity',
 'ASML NA Equity',
 'ASSAB SS Equity',
 'ATC NA Equity',
 'ATCOA SS Equity',
 'ATK LN Equity',
 'ATL IM Equity',
 'ATLN SW Equity',
 'ATO FP Equity',
 'AUTO LN Equity',
 'AV/ LN Equity',
 'AVOL SW Equity',
 'AZM IM Equity',
 'AZN LN Equity',
 'BA/ LN Equity',
 'BAB LN Equity',
 'BAER SW Equity',
 'BALDB SS Equity',
 'BALN SW Equity',
 'BARC LN Equity',
 'BARN SE Equity',
 'BAS GY Equity',
 'BATS LN Equity',
 'BAYN GY Equity',
 'BB FP Equity',
 'BBVA SQ Equity',
 'BBY LN Equity',
 'BEI GY Equity',
 'BEZ LN Equity',
 'BILL SS Equity',
 'BION SE Equity',
 'BIRG ID Equity',
 'BKG LN Equity',
 'BKIA SQ Equity',
 'BKT SQ Equity',
 'BLND LN Equity',
 'BME LN Equity',
 'BME SQ Equity',
 'BMW GY Equity',
 'BN FP Equity',
 'BNP FP Equity',
 'BNR GY Equity',
 'BNZL LN Equity',
 'BOK LN Equity',
 'BOKA NA Equity',
 'BOL FP Equity',
 'BOL SS Equity',
 'BOSS GY Equity',
 'BP IM Equity',
 'BP/ LN Equity',
 'BPE IM Equity',
 'BPOST BB Equity',
 'BRBY LN Equity',
 'BRSN LN Equity',
 'BT/A LN Equity',
 'BTRW LN Equity',
 'BVI FP Equity',
 'BVIC LN Equity',
 'BWY LN Equity',
 'CA FP Equity',
 'CABK SQ Equity',
 'CAP FP Equity',
 'CARLB DC Equity',
 'CAST SS Equity',
 'CBG LN Equity',
 'CBK GY Equity',
 'CCH LN Equity',
 'CCL LN Equity',
 'CDI FP Equity',
 'CEC GY Equity',
 'CEY LN Equity',
 'CEZ CK Equity',
 'CFR SW Equity',
 'CHR DC Equity',
 'CLLN LN Equity',
 'CLN SW Equity',
 'CLNX SQ Equity',
 'CNA LN Equity',
 'CNP FP Equity',
 'CO FP Equity',
 'COB LN Equity',
 'COFB BB Equity',
 'COLOB DC Equity',
 'COLR BB Equity',
 'CON GY Equity',
 'COV FP Equity',
 'CPG LN Equity',
 'CPI AV Equity',
 'CPI LN Equity',
 'CPR IM Equity',
 'CRDA LN Equity',
 'CRH ID Equity',
 'CS FP Equity',
 'CSGN SW Equity',
 'CURY LN Equity',
 'DANSKE DC Equity',
 'DB11 GY Equity',
 'DBK GY Equity',
 'DCC LN Equity',
 'DEC FP Equity',
 'DEMANT DC Equity',
 'DEQ GY Equity',
 'DG FP Equity',
 'DGE LN Equity',
 'DHL GY Equity',
 'DIA SQ Equity',
 'DKSH SE Equity',
 'DLG GY Equity',
 'DLG LN Equity',
 'DLN LN Equity',
 'DMGT LN Equity',
 'DNB NO Equity',
 'DOKA SE Equity',
 'DOM LN Equity',
 'DRX LN Equity',
 'DSM NA Equity',
 'DSV DC Equity',
 'DSY FP Equity',
 'DTE GY Equity',
 'DUE GY Equity',
 'DWNI GY Equity',
 'EBS AV Equity',
 'EDEN FP Equity',
 'EDF FP Equity',
 'EDP PL Equity',
 'EKTAB SS Equity',
 'EL FP Equity',
 'ELE SQ Equity',
 'ELIOR FP Equity',
 'ELISA FH Equity',
 'ELUXB SS Equity',
 'EMEIS FP Equity',
 'EMG LN Equity',
 'EMSN SE Equity',
 'EN FP Equity',
 'ENEL IM Equity',
 'ENG SQ Equity',
 'ENGI FP Equity',
 'ENI IM Equity',
 'ENT LN Equity',
 'ENX FP Equity',
 'EOAN GY Equity',
 'EQNR NO Equity',
 'ERF FP Equity',
 'ERICB SS Equity',
 'ESNT LN Equity',
 'ETL FP Equity',
 'EVK GY Equity',
 'EXO IM Equity',
 'EXPN LN Equity',
 'EZJ LN Equity',
 'FABG SS Equity',
 'FER SQ Equity',
 'FGP LN Equity',
 'FGR FP Equity',
 'FHZN SE Equity',
 'FINGB SS Equity',
 'FLTR ID Equity',
 'FME GY Equity',
 'FNTN GY Equity',
 'FORTUM FH Equity',
 'FPE3 GY Equity',
 'FR FP Equity',
 'FRA GY Equity',
 'FRE GY Equity',
 'FRES LN Equity',
 'FRVIA FP Equity',
 'G IM Equity',
 'G1A GY Equity',
 'GALP PL Equity',
 'GAM SE Equity',
 'GBF GY Equity',
 'GBLB BB Equity',
 'GEBN SW Equity',
 'GET FP Equity',
 'GETIB SS Equity',
 'GF SE Equity',
 'GFC FP Equity',
 'GFS LN Equity',
 'GFTU LN Equity',
 'GIVN SW Equity',
 'GJF NO Equity',
 'GKN LN Equity',
 'GLB ID Equity',
 'GLE FP Equity',
 'GLEN LN Equity',
 'GMAB DC Equity',
 'GN DC Equity',
 'GNK LN Equity',
 'GPE LN Equity',
 'GRF SQ Equity',
 'GSK LN Equity',
 'GTO NA Equity',
 'GXI GY Equity',
 'HAS LN Equity',
 'HBAN SE Equity',
 'HEI GY Equity',
 'HEIA NA Equity',
 'HEIO NA Equity',
 'HEN3 GY Equity',
 'HEXAB SS Equity',
 'HGG LN Equity',
 'HIK LN Equity',
 'HL/ LN Equity',
 'HLMA LN Equity',
 'HLUNB DC Equity',
 'HMB SS Equity',
 'HMSO LN Equity',
 'HNR1 GY Equity',
 'HO FP Equity',
 'HOLN SW Equity',
 'HOT GY Equity',
 'HPOLB SS Equity',
 'HSBA LN Equity',
 'HSX LN Equity',
 'HUH1V FH Equity',
 'HUSQB SS Equity',
 'HWDN LN Equity',
 'IAG LN Equity',
 'IAP LN Equity',
 'IBE SQ Equity',
 'ICA SS Equity',
 'ICAD FP Equity',
 'ICG LN Equity',
 'IDS LN Equity',
 'IFX GY Equity',
 'IGG LN Equity',
 'IHG LN Equity',
 'III LN Equity',
 'ILD FP Equity',
 'IMB LN Equity',
 'IMCD NA Equity',
 'IMI LN Equity',
 'INCH LN Equity',
 'INDUA SS Equity',
 'INDV LN Equity',
 'INF LN Equity',
 'ING FP Equity',
 'INGA NA Equity',
 'INTRUM SS Equity',
 'INTU LN Equity',
 'INVEB SS Equity',
 'INVP LN Equity',
 'IPN FP Equity',
 'ISAT LN Equity',
 'ISP IM Equity',
 'ISS DC Equity',
 'IT IM Equity',
 'ITRK LN Equity',
 'ITV LN Equity',
 'ITX SQ Equity',
 'JE/ LN Equity',
 'JM SS Equity',
 'JMAT LN Equity',
 'JMT PL Equity',
 'JUP LN Equity',
 'JYSK DC Equity',
 'KBC BB Equity',
 'KER FP Equity',
 'KESKOB FH Equity',
 'KGF LN Equity',
 'KGX GY Equity',
 'KINDSDB SS Equity',
 'KINVB SS Equity',
 'KN FP Equity',
 'KNEBV FH Equity',
 'KNIN SW Equity',
 'KOMB CK Equity',
 'KPN NA Equity',
 'KSP ID Equity',
 'KYGA ID Equity',
 'LAND LN Equity',
 'LDO IM Equity',
 'LEG GY Equity',
 'LGEN LN Equity',
 'LHA GY Equity',
 'LI FP Equity',
 'LISN SW Equity',
 'LLOY LN Equity',
 'LNA GY Equity',
 'LOGN SW Equity',
 'LONN SW Equity',
 'LR FP Equity',
 'LSEG LN Equity',
 'LUNDB SS Equity',
 'LUX IM Equity',
 'LXS GY Equity',
 'MAERSKB DC Equity',
 'MAN GY Equity',
 'MAP SQ Equity',
 'MB IM Equity',
 'MBG GY Equity',
 'MC FP Equity',
 'MCRO LN Equity',
 'MDC LN Equity',
 'MERL LN Equity',
 'MF FP Equity',
 'MFEB IM Equity',
 'MGGT LN Equity',
 'MKS LN Equity',
 'ML FP Equity',
 'MMB FP Equity',
 'MNDI LN Equity',
 'MONC IM Equity',
 'MONY LN Equity',
 'MOWI NO Equity',
 'MRK GY Equity',
 'MRL SQ Equity',
 'MRW LN Equity',
 'MT NA Equity',
 'MTX GY Equity',
 'MUV2 GY Equity',
 'NCCB SS Equity',
 'NDA SS Equity',
 'NELES FH Equity',
 'NESN SW Equity',
 'NESTE FH Equity',
 'NG/ LN Equity',
 'NHY NO Equity',
 'NIBEB SS Equity',
 'NK FP Equity',
 'NN NA Equity',
 'NOKIA FH Equity',
 'NOVN SW Equity',
 'NOVOB DC Equity',
 'NSISB DC Equity',
 'NTGY SQ Equity',
 'NWG LN Equity',
 'NXT LN Equity',
 'O2D GY Equity',
 'OCDO LN Equity',
 'OCI NA Equity',
 'OERL SE Equity',
 'OML LN Equity',
 'OMV AV Equity',
 'ONTEX BB Equity',
 'OPM FP Equity',
 'OR FP Equity',
 'ORA FP Equity',
 'ORK NO Equity',
 'ORNBV FH Equity',
 'ORRON SS Equity',
 'ORSTED DC Equity',
 'OSR GY Equity',
 'PAGE LN Equity',
 'PAH3 GY Equity',
 'PARG SE Equity',
 'PAYS LN Equity',
 'PFC LN Equity',
 'PGHN SW Equity',
 'PHIA NA Equity',
 'PHNX LN Equity',
 'PMI IM Equity',
 'PNDORA DC Equity',
 'PNL NA Equity',
 'PNN LN Equity',
 'POLY LN Equity',
 'POP SQ Equity',
 'PROX BB Equity',
 'PRU LN Equity',
 'PRY IM Equity',
 'PSM GY Equity',
 'PSN LN Equity',
 'PSON LN Equity',
 'PSPN SE Equity',
 'PST IM Equity',
 'PTEC LN Equity',
 'PUB FP Equity',
 'QIA GY Equity',
 'QQ/ LN Equity',
 'RACE IM Equity',
 'RAND NA Equity',
 'RBI AV Equity',
 'RDSA NA Equity',
 'REC IM Equity',
 'RED SQ Equity',
 'REL LN Equity',
 'RENT NA Equity',
 'REP SQ Equity',
 'RF FP Equity',
 'RGU LN Equity',
 'RHM GY Equity',
 'RI FP Equity',
 'RIO LN Equity',
 'RKT LN Equity',
 'RMS FP Equity',
 'RMV LN Equity',
 'RNO FP Equity',
 'ROG SW Equity',
 'ROR LN Equity',
 'RPC LN Equity',
 'RR/ LN Equity',
 'RRS LN Equity',
 'RRTL GY Equity',
 'RSA LN Equity',
 'RTO LN Equity',
 'RUI FP Equity',
 'RWE GY Equity',
 'RXL FP Equity',
 'RYA ID Equity',
 'SAABB SS Equity',
 'SAB LN Equity',
 'SAB SQ Equity',
 'SAF FP Equity',
 'SAGA LN Equity',
 'SAMPO FH Equity',
 'SAN FP Equity',
 'SAN SQ Equity',
 'SAND SS Equity',
 'SAP GY Equity',
 'SAZ GY Equity',
 'SBMO NA Equity',
 'SBRY LN Equity',
 'SCAB SS Equity',
 'SCHP SW Equity',
 'SCMN SW Equity',
 'SCR FP Equity',
 'SDF GY Equity',
 'SDR LN Equity',
 'SEBA SS Equity',
 'SECUB SS Equity',
 'SESG FP Equity',
 'SEV FP Equity',
 'SFR FP Equity',
 'SGE LN Equity',
 'SGO FP Equity',
 'SGRE SQ Equity',
 'SGRO LN Equity',
 'SGSN SW Equity',
 'SHB LN Equity',
 'SHBA SS Equity',
 'SHC LN Equity',
 'SHP LN Equity',
 'SIE GY Equity',
 'SIG LN Equity',
 'SIKA SW Equity',
 'SK FP Equity',
 'SKAB SS Equity',
 'SKFB SS Equity',
 'SKG ID Equity',
 'SKY LN Equity',
 'SLHN SW Equity',
 'SMDS LN Equity',
 'SMIN LN Equity',
 'SMWH LN Equity',
 'SN/ LN Equity',
 'SNH GY Equity',
 'SOBI SS Equity',
 'SOLB BB Equity',
 'SOON SW Equity',
 'SPM IM Equity',
 'SPR GY Equity',
 'SPSN SE Equity',
 'SPX LN Equity',
 'SRCG SE Equity',
 'SREN SW Equity',
 'SRG IM Equity',
 'SRT3 GY Equity',
 'SSE LN Equity',
 'STAN LN Equity',
 'STERV FH Equity',
 'STJ LN Equity',
 'STLAM IM Equity',
 'STMMI IM Equity',
 'STMN SE Equity',
 'SU FP Equity',
 'SUBC NO Equity',
 'SVT LN Equity',
 'SW FP Equity',
 'SWEDA SS Equity',
 'SWMA SS Equity',
 'SXS LN Equity',
 'SY1 GY Equity',
 'SYNN SW Equity',
 'TALK LN Equity',
 'TATE LN Equity',
 'TDC DC Equity',
 'TEC FP Equity',
 'TEF SQ Equity',
 'TEL NO Equity',
 'TEL2B SS Equity',
 'TELIA SS Equity',
 'TEMN SE Equity',
 'TEN IM Equity',
 'TEP FP Equity',
 'TIT IM Equity',
 'TKA GY Equity',
 'TL5 SQ Equity',
 'TLW LN Equity',
 'TNET BB Equity',
 'TOP DC Equity',
 'TPK LN Equity',
 'TRELB SS Equity',
 'TRN IM Equity',
 'TRYG DC Equity',
 'TSCO LN Equity',
 'TTE FP Equity',
 'TUI LN Equity',
 'TW/ LN Equity',
 'TYRES FH Equity',
 'UBI FP Equity',
 'UBI IM Equity',
 'UBM LN Equity',
 'UBSG SW Equity',
 'UCB BB Equity',
 'UCG IM Equity',
 'UG FP Equity',
 'UHR SW Equity',
 'UL NA Equity',
 'ULE LN Equity',
 'ULVR LN Equity',
 'UMI BB Equity',
 'UN0 GY Equity',
 'UPM FH Equity',
 'US IM Equity',
 'UTDI GY Equity',
 'UU/ LN Equity',
 'VANQ LN Equity',
 'VANTI FP Equity',
 'VCT LN Equity',
 'VENDA NO Equity',
 'VIE FP Equity',
 'VIFN SW Equity',
 'VIS SQ Equity',
 'VIV FP Equity',
 'VMUK LN Equity',
 'VNA GY Equity',
 'VOD LN Equity',
 'VOE AV Equity',
 'VOLVB SS Equity',
 'VOW3 GY Equity',
 'VPK NA Equity',
 'VTY LN Equity',
 'VWS DC Equity',
 'WDI GY Equity',
 'WEIR LN Equity',
 'WG/ LN Equity',
 'WHA NA Equity',
 'WIE AV Equity',
 'WKL NA Equity',
 'WMH LN Equity',
 'WPG LN Equity',
 'WPP LN Equity',
 'WRT1V FH Equity',
 'WTB LN Equity',
 'YAR NO Equity',
 'ZAL GY Equity',
 'ZC FP Equity',
 'ZOT SQ Equity',
 'ZURN SW Equity',
 'MRO LN Equity',
 'SOW GY Equity',
 'IG IM Equity',
 'BWO AV Equity',
 'CMBN SE Equity',
 'DL NA Equity',
 'GLPG NA Equity',
 'IGY GY Equity',
 'IWG LN Equity',
 'NETS DC Equity',
 'NXG LN Equity',
 'SIM DC Equity',
 'STB NO Equity',
 'BAMI IM Equity',
 'FTI FP Equity',
 'OUT1V FH Equity',
 '2261689D LN Equity',
 'FBK IM Equity',
 'G24 GY Equity',
 'LCL LN Equity',
 'RS1 LN Equity',
 'SSPG LN Equity',
 'TCAP LN Equity',
 'TGS NO Equity',
 'AMUN FP Equity',
 'DB1 GY Equity',
 'ATLN SE Equity',
 'CTEC LN Equity',
 'LIGHT NA Equity',
 'BIM FP Equity',
 'ESSITYB SS Equity',
 'LOOMIS SS Equity',
 'SOP FP Equity',
 'B4B GY Equity',
 'UDG LN Equity',
 '1U1 GY Equity',
 'AIBG ID Equity',
 'ASRNL NA Equity',
 'LISN SE Equity',
 'NDA GY Equity',
 'SPIE FP Equity',
 'ABBN SE Equity',
 'ADEN SE Equity',
 'ARYN SE Equity',
 'AT1 GY Equity',
 'AVOL SE Equity',
 'BAER SE Equity',
 'BALN SE Equity',
 'CFR SE Equity',
 'CLN SE Equity',
 'CSGN SE Equity',
 'ELIS FP Equity',
 'GEBN SE Equity',
 'GIVN SE Equity',
 'HOLN SE Equity',
 'KNIN SE Equity',
 'LOGN SE Equity',
 'LONN SE Equity',
 'NESN SE Equity',
 'NOVN SE Equity',
 'PGHN SE Equity',
 'ROG SE Equity',
 'SCHP SE Equity',
 'SCMN SE Equity',
 'SGSN SE Equity',
 'SIKA SE Equity',
 'SLHN SE Equity',
 'SOON SE Equity',
 'SREN SE Equity',
 'UBSG SE Equity',
 'UHR SE Equity',
 'VIFN SE Equity',
 'ZURN SE Equity',
 'ALT FP Equity',
 'BESI NA Equity',
 'DHER GY Equity',
 'HSV LN Equity',
 'KCR FH Equity',
 'LINU GY Equity',
 'NMC LN Equity',
 'PIRC IM Equity',
 'RCO FP Equity',
 'VACN SE Equity',
 'WAF GY Equity',
 'WCH GY Equity',
 'ABLX BB Equity',
 'AKRBP NO Equity',
 'AMBUB DC Equity',
 'BCP PL Equity',
 'BUCN SE Equity',
 'COL SQ Equity',
 'DOM SS Equity',
 'DPH LN Equity',
 'GLJ GY Equity',
 'HLE GY Equity',
 'AVV LN Equity',
 'ARGX BB Equity',
 'ATE FP Equity',
 'CINE LN Equity',
 'EPIA SS Equity',
 'EVR LN Equity',
 'FLS DC Equity',
 'KAZ LN Equity',
 'MOR GY Equity',
 'OMU LN Equity',
 'QLT LN Equity',
 'RBREW DC Equity',
 'ROCKB DC Equity',
 'SHL GY Equity',
 'TECN SE Equity',
 'TEG GY Equity',
 'URW NA Equity',
 'AAK SS Equity',
 'ADYEN NA Equity',
 'AFX GY Equity',
 'BBOX LN Equity',
 'BC8 GY Equity',
 'CDR PW Equity',
 'DIA IM Equity',
 'DIM FP Equity',
 'EVT GY Equity',
 'GALE SE Equity',
 'KGH PW Equity',
 'LPP PW Equity',
 'NEM GY Equity',
 'PEO PW Equity',
 'PKN PW Equity',
 'PKO PW Equity',
 'PUM GY Equity',
 'PZU PW Equity',
 'SOF BB Equity',
 'SPL PW Equity',
 'UTG LN Equity',
 'VALMT FH Equity',
 'JLT LN Equity',
 'LIN GY Equity',
 'VER AV Equity',
 'IP IM Equity',
 'KBX GY Equity',
 'PGN PW Equity',
 'SALM NO Equity',
 'TOM NO Equity',
 'HER IM Equity',
 'TKWY NA Equity',
 'ALC SE Equity',
 'WDP BB Equity',
 'WLN FP Equity',
 'AMP IM Equity',
 'ASHM LN Equity',
 'BEAN SE Equity',
 'GRG LN Equity',
 'GYC GY Equity',
 'INDT SS Equity',
 'JD/ LN Equity',
 'UNAT NA Equity',
 'AED BB Equity',
 'ALLN SE Equity',
 'AOX GY Equity',
 'ELI BB Equity',
 'EVD GY Equity',
 'NEXI IM Equity',
 'MNG LN Equity',
 'PRX NA Equity',
 'KOJAMO FH Equity',
 'AVST LN Equity',
 'EQT SS Equity',
 'EVO SS Equity',
 'HFG GY Equity',
 'HOLMB SS Equity',
 'NETW LN Equity',
 'SIGN SE Equity',
 'BAKKA NO Equity',
 'DPLM LN Equity',
 'ANA SQ Equity',
 'BG AV Equity',
 'CSP LN Equity',
 'ENTRA NO Equity',
 'FDJU FP Equity',
 'GAW LN Equity',
 'GNS LN Equity',
 'RAA GY Equity',
 'RDW LN Equity',
 'SBBB SS Equity',
 'TMV GY Equity',
 'TRN LN Equity',
 'WIHL SS Equity',
 'ADDTB SS Equity',
 'ADE NO Equity',
 'AGR LN Equity',
 'AXFO SS Equity',
 'BCVN SE Equity',
 'COK GY Equity',
 'CWK LN Equity',
 'GRI LN Equity',
 'IDIA SE Equity',
 'LATOB SS Equity',
 'LIFCOB SS Equity',
 'NETC DC Equity',
 'PHP LN Equity',
 'SINCH SS Equity',
 'SWECB SS Equity',
 'THULE SS Equity',
 'WALLB SS Equity',
 'METSO FH Equity',
 'ADJ GY Equity',
 'AFRY SS Equity',
 'BEIJB SS Equity',
 'CRBN NA Equity',
 'DNP PW Equity',
 'ENR GY Equity',
 'INW IM Equity',
 'JDEP NA Equity',
 'LMP LN Equity',
 'MAS SQ Equity',
 'NEL NO Equity',
 'SOI FP Equity',
 'SRAIL SE Equity',
 'SWON SE Equity',
 'VAR1 GY Equity',
 'DOCM SE Equity',
 'EDPR PL Equity',
 'SFZN SE Equity',
 'ALE PW Equity',
 'SAGAB SS Equity',
 'SCATC NO Equity',
 'THG LN Equity',
 'VPLAYB SS Equity',
 'AZA SS Equity',
 'INPST NA Equity',
 'NOD NO Equity',
 'RDC GY Equity',
 'WIZZ LN Equity',
 'SCT LN Equity',
 'AG1 GY Equity',
 'ALLFG NA Equity',
 'DOCS LN Equity',
 'FDR SQ Equity',
 'FUTR LN Equity',
 'REY IM Equity',
 'ROO LN Equity',
 'SFOR LN Equity',
 'TIGO SS Equity',
 'ALIFB SS Equity',
 'BANB SE Equity',
 'ARCAD NA Equity',
 'BPT LN Equity',
 'BYG LN Equity',
 'NDA FH Equity',
 'QTCOM FH Equity',
 'UMG NA Equity',
 'VITR SS Equity',
 'WISE LN Equity',
 'DARK LN Equity',
 'ZO1 GY Equity',
 'ALKB DC Equity',
 'AUTO NO Equity',
 'DIE BB Equity',
 'DTG GY Equity',
 'INRN SE Equity',
 'MIPS SS Equity',
 'ONT LN Equity',
 'RILBA DC Equity',
 'SAFE LN Equity',
 'SECTB SS Equity',
 'STORB SS Equity',
 'VOLCARB SS Equity',
 'WOSG LN Equity',
 'IVG IM Equity',
 'SHELL NA Equity',
 'KOG NO Equity',
 'OSB LN Equity',
 'SSABB SS Equity',
 'VTWR GY Equity',
 'AIXA GY Equity',
 'FNOX SS Equity',
 'GTT FP Equity',
 'HBR LN Equity',
 'NEX FP Equity',
 'SAVE SS Equity',
 'HLN LN Equity',
 'ALLEI SS Equity',
 'ALFEN NA Equity',
 'ANE SQ Equity',
 'BAVA DC Equity',
 'BKW SE Equity',
 'CCC LN Equity',
 'ECV GY Equity',
 'EXO NA Equity',
 'INDUC SS Equity',
 'LISP SE Equity',
 'LOTB BB Equity',
 'LXI LN Equity',
 'SRP LN Equity',
 'TIETO FH Equity',
 'ENOG LN Equity',
 'HTRO SS Equity',
 'P911 GY Equity',
 'TLX GY Equity',
 'VRLA FP Equity',
 'BC IM Equity',
 'CMBT BB Equity',
 'EMBRACB SS Equity',
 'FRO NO Equity',
 'TE FP Equity',
 'VID SQ Equity',
 'DSFIR NA Equity',
 'DWL LN Equity',
 'URW FP Equity',
 'AZE BB Equity',
 'LAGRB SS Equity',
 'NKT DC Equity',
 'SFSN SE Equity',
 'ACLN SE Equity',
 'BZU IM Equity',
 'CRH LN Equity',
 'SDZ SE Equity',
 'BMPS IM Equity',
 'FLTR LN Equity',
 'SQN SE Equity',
 'SYENS BB Equity',
 'VK FP Equity',
 'ZEAL DC Equity',
 'BBVA SM Equity',
 'BPSO IM Equity',
 'COTN SE Equity',
 'HEM SS Equity',
 'HIAB FH Equity',
 'IBE SM Equity',
 'IFCN SE Equity',
 'IPS FP Equity',
 'ITX SM Equity',
 'SAN SM Equity',
 'UNI IM Equity',
 'SVITZR DC Equity',
 'FUR NA Equity',
 'GALD SE Equity',
 'KEMIRA FH Equity',
 'MTRS SS Equity',
 'MYCR SS Equity',
 'NEOEN FP Equity',
 'TUI1 GY Equity',
 'VAR NO Equity',
 'BMED IM Equity',
 'CVC NA Equity',
 'PUIG SQ Equity',
 'TUB BB Equity',
 'SUN SE Equity',
 'BGN IM Equity',
 'CAN LN Equity',
 'SB1NO NO Equity',
 'VZN SE Equity',
 'PLUS LN Equity',
 'HAG GY Equity',
 'MANTA FH Equity',
 'SUNN SE Equity',
 'TBCG LN Equity',
 'R3NK GY Equity',
 'AMRZ SE Equity',
 'AYV FP Equity',
 'BGEO LN Equity',
 'IDR SQ Equity',
 'LTMC IM Equity',
 'MBK PW Equity',
 'MOBN SE Equity',
 'KBCA BB Equity',
 'ABVX FP Equity',
 'AMV0 GY Equity',
 'CAMX SS Equity',
 'FTK GY Equity',
 'NDX1 GY Equity',
 'UNI SQ Equity',
 'ZEG LN Equity',
 'AAF LN Equity',
 'ACP PW Equity',
 'DLG IM Equity',
 'HUBN SE Equity',
 'MICC NA Equity',
 'MTO LN Equity',
 'VEND NO Equity',
 'VSURE SS Equity']

Requete informations sur tickers


## 4. Requete des informations sur l'historique des composants de l'Indice Univers <a id='1'></a>

In [ ]:
from request.request_informations_members import BloombergTickerInfo 

# téléchargement
info = BloombergTickerInfo(verbose=True)

df_info = info.fetch(tickers_equity)

# sauvegarde
info.save_parquet(df_info)

Parquet sauvegardé : C:\Users\lenar25\Documents\Backtesting_M2272\data\initial_data\informations_hist_memb_index.parquet

WindowsPath('C:/Users/lenar25/Documents/Backtesting_M2272/data/initial_data/informations_hist_memb_index.parquet')

In [ ]:
# Visualisation
stockage = ParquetStockage()

informations_hist_memb_index = stockage.charger("informations_hist_memb_index")

informations_hist_memb_index.tail()

,Ticker,Name,Currency,Sector,Industry,Country
975,ABVX FP Equity,ABIVAX SA,EUR,Soins de santé,Biotechnologie,FRANCE
976,AMV0 GY Equity,AUMOVIO SE,EUR,Consommation discrétionnaire,Composants automobiles,GERMANY
977,CAMX SS Equity,CAMURUS AB,SEK,Soins de santé,Produits pharmaceutiques,SWEDEN
978,FTK GY Equity,FLATEXDEGIRO SE,EUR,Finance,Marchés de capitaux,GERMANY
979,NDX1 GY Equity,NORDEX SE,EUR,Industrie,Matériel électrique,GERMANY

In [ ]:
# exporter pour vérification en excel
exporter = ExportData(folder_type="verification")
exporter.export_df(informations_hist_memb_index, "informations_hist_memb_index")

WindowsPath('C:/Users/lenar25/Documents/Backtesting_M2272/data/verification/informations_hist_memb_index_20260226_194944.xlsx')

 Requeter l'historique


## 5. Requete des historique des prix des composants de l'Indice Univers <a id='1'></a>

In [ ]:
from request.request_historical_data import BloombergPXLastHistory

# fonction de téléchargement des prix de clôture 
px = BloombergPXLastHistory(verbose=True)


df_prices = px.fetch(tickers=tickers_equity, start="2015-09-01", end="2026-02-20", frequency="DAILY")

df_prices.tail()

# sauvegarde dans un fichier de stockage
px.save_parquet(df_prices)

OK: 1844030D NA Equity -> 979 points
OK: 1986986D LN Equity -> 1623 points
OK: 1CNHI IM Equity -> 2661 points
OK: 1COV GY Equity -> 2594 points
OK: 2462936D LN Equity -> 2253 points
OK: 2578464D GY Equity -> 2279 points
OK: 2627525D LN Equity -> 1004 points
OK: A2A IM Equity -> 2661 points
OK: AA/ LN Equity -> 1398 points
OK: AAL LN Equity -> 2648 points
OK: AALB NA Equity -> 2683 points
OK: ABBN SW Equity -> 2633 points
OK: ABDN LN Equity -> 2648 points
OK: ABE SQ Equity -> 750 points
OK: ABF LN Equity -> 2648 points
OK: ABI BB Equity -> 2683 points
OK: ABN NA Equity -> 2626 points
OK: AC FP Equity -> 2683 points
OK: ACA FP Equity -> 2683 points
OK: ACKB BB Equity -> 2683 points
OK: ACS SQ Equity -> 2681 points
OK: AD NA Equity -> 2683 points
OK: ADEN SW Equity -> 2633 points
OK: ADM LN Equity -> 2648 points
OK: ADN LN Equity -> 494 points
OK: ADP FP Equity -> 2683 points
OK: ADS GY Equity -> 2658 points
OK: AENA SQ Equity -> 2681 points
OK: AF FP Equity -> 2683 points
OK: AGK LN Equity -> 1504 points
OK: AGN NA Equity -> 2683 points
OK: AGS BB Equity -> 2683 points
OK: AHT LN Equity -> 2648 points
OK: AI FP Equity -> 2683 points
OK: AIR FP Equity -> 2683 points
OK: AKE FP Equity -> 2683 points
OK: AKZA NA Equity -> 2683 points
OK: ALFA SS Equity -> 2633 points
OK: ALO FP Equity -> 2683 points
OK: ALSYDB DC Equity -> 2622 points
OK: ALV GY Equity -> 2658 points
OK: AM FP Equity -> 2683 points
OK: AMEAS FH Equity -> 1003 points
OK: AMFW LN Equity -> 533 points
OK: AMS SE Equity -> 2633 points
OK: AMS SQ Equity -> 2681 points
OK: ANDR AV Equity -> 2641 points
OK: ANTO LN Equity -> 2648 points
OK: ARLN GY Equity -> 2089 points
OK: ARYN SW Equity -> 2633 points
OK: ASM NA Equity -> 2683 points
OK: ASML NA Equity -> 2683 points
OK: ASSAB SS Equity -> 2633 points
OK: ATC NA Equity -> 1383 points
OK: ATCOA SS Equity -> 2633 points
OK: ATK LN Equity -> 464 points
OK: ATL IM Equity -> 1850 points
OK: ATLN SW Equity -> 553 points
OK: ATO FP Equity -> 2683 points
OK: AUTO LN Equity -> 2648 points
OK: AV/ LN Equity -> 2648 points
OK: AVOL SW Equity -> 2633 points
OK: AZM IM Equity -> 2661 points
OK: AZN LN Equity -> 2648 points
OK: BA/ LN Equity -> 2648 points
OK: BAB LN Equity -> 2648 points
OK: BAER SW Equity -> 2633 points
OK: BALDB SS Equity -> 2633 points
OK: BALN SW Equity -> 2584 points
OK: BARC LN Equity -> 2648 points
OK: BARN SE Equity -> 2633 points
OK: BAS GY Equity -> 2658 points
OK: BATS LN Equity -> 2648 points
OK: BAYN GY Equity -> 2658 points
OK: BB FP Equity -> 2683 points
OK: BBVA SQ Equity -> 2681 points
OK: BBY LN Equity -> 2648 points
OK: BEI GY Equity -> 2658 points
OK: BEZ LN Equity -> 2648 points
OK: BILL SS Equity -> 2633 points
OK: BION SE Equity -> 2633 points
OK: BIRG ID Equity -> 2667 points
OK: BKG LN Equity -> 2648 points
OK: BKIA SQ Equity -> 1426 points
OK: BKT SQ Equity -> 2681 points
OK: BLND LN Equity -> 2648 points
OK: BME LN Equity -> 2648 points
OK: BME SQ Equity -> 1300 points
OK: BMW GY Equity -> 2658 points
OK: BN FP Equity -> 2683 points
OK: BNP FP Equity -> 2683 points
OK: BNR GY Equity -> 2658 points
OK: BNZL LN Equity -> 2648 points
OK: BOK LN Equity -> 635 points
OK: BOKA NA Equity -> 1844 points
OK: BOL FP Equity -> 2683 points
OK: BOL SS Equity -> 2633 points
OK: BOSS GY Equity -> 2658 points
OK: BP IM Equity -> 341 points
OK: BP/ LN Equity -> 2648 points
OK: BPE IM Equity -> 2661 points
OK: BPOST BB Equity -> 2683 points
OK: BRBY LN Equity -> 2648 points
OK: BRSN LN Equity -> 514 points
OK: BT/A LN Equity -> 2648 points
OK: BTRW LN Equity -> 2648 points
OK: BVI FP Equity -> 2683 points
OK: BVIC LN Equity -> 2371 points
OK: BWY LN Equity -> 2648 points
OK: CA FP Equity -> 2683 points
OK: CABK SQ Equity -> 2681 points
OK: CAP FP Equity -> 2683 points
OK: CARLB DC Equity -> 2622 points
OK: CAST SS Equity -> 2633 points
OK: CBG LN Equity -> 2648 points
OK: CBK GY Equity -> 2658 points
OK: CCH LN Equity -> 2648 points
OK: CCL LN Equity -> 2648 points
OK: CDI FP Equity -> 2683 points
OK: CEC GY Equity -> 2658 points
OK: CEY LN Equity -> 2334 points
OK: CEZ CK Equity -> 2623 points
OK: CFR SW Equity -> 2633 points
OK: CHR DC Equity -> 2108 points
OK: CLLN LN Equity -> 601 points
OK: CLN SW Equity -> 2633 points
OK: CLNX SQ Equity -> 2681 points
OK: CNA LN Equity -> 2648 points
OK: CNP FP Equity -> 1731 points
OK: CO FP Equity -> 2683 points
OK: COB LN Equity -> 1109 points
OK: COFB BB Equity -> 2682 points
OK: COLOB DC Equity -> 2622 points
OK: COLR BB Equity -> 2683 points
OK: CON GY Equity -> 2658 points
OK: COV FP Equity -> 2683 points
OK: CPG LN Equity -> 2648 points
OK: CPI AV Equity -> 2641 points
OK: CPI LN Equity -> 2648 points
OK: CPR IM Equity -> 2661 points
OK: CRDA LN Equity -> 2648 points
OK: CRH ID Equity -> 2055 points
OK: CS FP Equity -> 2683 points
OK: CSGN SW Equity -> 1959 points
OK: CURY LN Equity -> 2648 points
OK: DANSKE DC Equity -> 2622 points
OK: DB11 GY Equity -> 206 points
OK: DBK GY Equity -> 2658 points
OK: DCC LN Equity -> 2648 points
OK: DEC FP Equity -> 2683 points
OK: DEMANT DC Equity -> 2622 points
OK: DEQ GY Equity -> 2658 points
OK: DG FP Equity -> 2683 points
OK: DGE LN Equity -> 2648 points
OK: DHL GY Equity -> 2658 points
OK: DIA SQ Equity -> 2681 points
OK: DKSH SE Equity -> 2633 points
OK: DLG GY Equity -> 1516 points
OK: DLG LN Equity -> 2485 points
OK: DLN LN Equity -> 2648 points
OK: DMGT LN Equity -> 1608 points
OK: DNB NO Equity -> 2631 points
OK: DOKA SE Equity -> 2633 points
OK: DOM LN Equity -> 2648 points
OK: DRX LN Equity -> 2648 points
OK: DSM NA Equity -> 1986 points
OK: DSV DC Equity -> 2622 points
OK: DSY FP Equity -> 2683 points
OK: DTE GY Equity -> 2658 points
OK: DUE GY Equity -> 2658 points
OK: DWNI GY Equity -> 2658 points
OK: EBS AV Equity -> 2641 points
OK: EDEN FP Equity -> 2683 points
OK: EDF FP Equity -> 1988 points
OK: EDP PL Equity -> 2683 points
OK: EKTAB SS Equity -> 2633 points
OK: EL FP Equity -> 2683 points
OK: ELE SQ Equity -> 2681 points
OK: ELIOR FP Equity -> 2682 points
OK: ELISA FH Equity -> 2633 points
OK: ELUXB SS Equity -> 2633 points
OK: EMEIS FP Equity -> 2681 points
OK: EMG LN Equity -> 2648 points
OK: EMSN SE Equity -> 2633 points
OK: EN FP Equity -> 2683 points
OK: ENEL IM Equity -> 2661 points
OK: ENG SQ Equity -> 2681 points
OK: ENGI FP Equity -> 2683 points
OK: ENI IM Equity -> 2661 points
OK: ENT LN Equity -> 2648 points
OK: ENX FP Equity -> 2683 points
OK: EOAN GY Equity -> 2658 points
OK: EQNR NO Equity -> 2631 points
OK: ERF FP Equity -> 2682 points
OK: ERICB SS Equity -> 2633 points
OK: ESNT LN Equity -> 2648 points
OK: ETL FP Equity -> 2683 points
OK: EVK GY Equity -> 2658 points
OK: EXO IM Equity -> 1798 points
OK: EXPN LN Equity -> 2648 points
OK: EZJ LN Equity -> 2648 points
OK: FABG SS Equity -> 2633 points
OK: FER SQ Equity -> 2681 points
OK: FGP LN Equity -> 2648 points
OK: FGR FP Equity -> 2683 points
OK: FHZN SE Equity -> 2633 points
OK: FINGB SS Equity -> 2633 points
OK: FLTR ID Equity -> 2142 points
OK: FME GY Equity -> 2658 points
OK: FNTN GY Equity -> 2658 points
OK: FORTUM FH Equity -> 2633 points
OK: FPE3 GY Equity -> 2658 points
OK: FR FP Equity -> 2683 points
OK: FRA GY Equity -> 2658 points
OK: FRE GY Equity -> 2658 points
OK: FRES LN Equity -> 2648 points
OK: FRVIA FP Equity -> 2682 points
OK: G IM Equity -> 2661 points
OK: G1A GY Equity -> 2658 points
OK: GALP PL Equity -> 2683 points
OK: GAM SE Equity -> 2633 points
OK: GBF GY Equity -> 2658 points
OK: GBLB BB Equity -> 2683 points
OK: GEBN SW Equity -> 2633 points
OK: GET FP Equity -> 2683 points
OK: GETIB SS Equity -> 2633 points
OK: GF SE Equity -> 2633 points
OK: GFC FP Equity -> 2683 points
OK: GFS LN Equity -> 1435 points
OK: GFTU LN Equity -> 2648 points
OK: GIVN SW Equity -> 2633 points
OK: GJF NO Equity -> 2630 points
OK: GKN LN Equity -> 687 points
OK: GLB ID Equity -> 2667 points
OK: GLE FP Equity -> 2683 points
OK: GLEN LN Equity -> 2648 points
OK: GMAB DC Equity -> 2622 points
OK: GN DC Equity -> 2622 points
OK: GNK LN Equity -> 1055 points
OK: GPE LN Equity -> 2648 points
OK: GRF SQ Equity -> 2681 points
OK: GSK LN Equity -> 2648 points
OK: GTO NA Equity -> 956 points
OK: GXI GY Equity -> 2658 points
OK: HAS LN Equity -> 2648 points
OK: HBAN SE Equity -> 2633 points
OK: HEI GY Equity -> 2658 points
OK: HEIA NA Equity -> 2683 points
OK: HEIO NA Equity -> 2683 points
OK: HEN3 GY Equity -> 2658 points
OK: HEXAB SS Equity -> 2633 points
OK: HGG LN Equity -> 440 points
OK: HIK LN Equity -> 2648 points
OK: HL/ LN Equity -> 2417 points
OK: HLMA LN Equity -> 2648 points
OK: HLUNB DC Equity -> 2622 points
OK: HMB SS Equity -> 2633 points
OK: HMSO LN Equity -> 2648 points
OK: HNR1 GY Equity -> 2658 points
OK: HO FP Equity -> 2683 points
OK: HOLN SW Equity -> 2633 points
OK: HOT GY Equity -> 2658 points
OK: HPOLB SS Equity -> 2633 points
OK: HSBA LN Equity -> 2648 points
OK: HSX LN Equity -> 2648 points
OK: HUH1V FH Equity -> 2633 points
OK: HUSQB SS Equity -> 2633 points
OK: HWDN LN Equity -> 2648 points
OK: IAG LN Equity -> 2648 points
OK: IAP LN Equity -> 329 points
OK: IBE SQ Equity -> 2681 points
OK: ICA SS Equity -> 1602 points
OK: ICAD FP Equity -> 2683 points
OK: ICG LN Equity -> 2648 points
OK: IDS LN Equity -> 2462 points
OK: IFX GY Equity -> 2658 points
OK: IGG LN Equity -> 2648 points
OK: IHG LN Equity -> 2648 points
OK: III LN Equity -> 2648 points
OK: ILD FP Equity -> 1556 points
OK: IMB LN Equity -> 2648 points
OK: IMCD NA Equity -> 2683 points
OK: IMI LN Equity -> 2648 points
OK: INCH LN Equity -> 2648 points
OK: INDUA SS Equity -> 2633 points
OK: INDV LN Equity -> 2501 points
OK: INF LN Equity -> 2648 points
OK: ING FP Equity -> 1328 points
OK: INGA NA Equity -> 2683 points
OK: INTRUM SS Equity -> 2633 points
OK: INTU LN Equity -> 1220 points
OK: INVEB SS Equity -> 2633 points
OK: INVP LN Equity -> 2648 points
OK: IPN FP Equity -> 2683 points
OK: ISAT LN Equity -> 1080 points
OK: ISP IM Equity -> 2661 points
OK: ISS DC Equity -> 2622 points
OK: IT IM Equity -> 283 points
OK: ITRK LN Equity -> 2648 points
OK: ITV LN Equity -> 2648 points
OK: ITX SQ Equity -> 2681 points
OK: JE/ LN Equity -> 1120 points
OK: JM SS Equity -> 2633 points
OK: JMAT LN Equity -> 2648 points
OK: JMT PL Equity -> 2683 points
OK: JUP LN Equity -> 2648 points
OK: JYSK DC Equity -> 2622 points
OK: KBC BB Equity -> 2683 points
OK: KER FP Equity -> 2683 points
OK: KESKOB FH Equity -> 2633 points
OK: KGF LN Equity -> 2648 points
OK: KGX GY Equity -> 2658 points
OK: KINDSDB SS Equity -> 2317 points
OK: KINVB SS Equity -> 2633 points
OK: KN FP Equity -> 1498 points
OK: KNEBV FH Equity -> 2633 points
OK: KNIN SW Equity -> 2633 points
OK: KOMB CK Equity -> 2623 points
OK: KPN NA Equity -> 2683 points
OK: KSP ID Equity -> 2667 points
OK: KYGA ID Equity -> 2667 points
OK: LAND LN Equity -> 2648 points
OK: LDO IM Equity -> 2661 points
OK: LEG GY Equity -> 2658 points
OK: LGEN LN Equity -> 2648 points
OK: LHA GY Equity -> 2658 points
OK: LI FP Equity -> 2683 points
OK: LISN SW Equity -> 2633 points
OK: LLOY LN Equity -> 2648 points
OK: LNA GY Equity -> 912 points
OK: LOGN SW Equity -> 2633 points
OK: LONN SW Equity -> 2633 points
OK: LR FP Equity -> 2683 points
OK: LSEG LN Equity -> 2648 points
OK: LUNDB SS Equity -> 2633 points
OK: LUX IM Equity -> 890 points
OK: LXS GY Equity -> 2658 points
OK: MAERSKB DC Equity -> 2622 points
OK: MAN GY Equity -> 1517 points
OK: MAP SQ Equity -> 2681 points
OK: MB IM Equity -> 2661 points
OK: MBG GY Equity -> 2658 points
OK: MC FP Equity -> 2683 points
OK: MCRO LN Equity -> 1875 points
OK: MDC LN Equity -> 1954 points
OK: MERL LN Equity -> 1058 points
OK: MF FP Equity -> 2683 points
OK: MFEB IM Equity -> 2661 points
OK: MGGT LN Equity -> 1779 points
OK: MKS LN Equity -> 2648 points
OK: ML FP Equity -> 2683 points
OK: MMB FP Equity -> 2683 points
OK: MNDI LN Equity -> 2648 points
OK: MONC IM Equity -> 2661 points
OK: MONY LN Equity -> 2648 points
OK: MOWI NO Equity -> 2631 points
OK: MRK GY Equity -> 2658 points
OK: MRL SQ Equity -> 2681 points
OK: MRW LN Equity -> 1559 points
OK: MT NA Equity -> 2683 points
OK: MTX GY Equity -> 2658 points
OK: MUV2 GY Equity -> 2658 points
OK: NCCB SS Equity -> 2633 points
OK: NDA SS Equity -> 2633 points
OK: NELES FH Equity -> 1656 points
OK: NESN SW Equity -> 2633 points
OK: NESTE FH Equity -> 2633 points
OK: NG/ LN Equity -> 2648 points
OK: NHY NO Equity -> 2631 points
OK: NIBEB SS Equity -> 2633 points
OK: NK FP Equity -> 2683 points
OK: NN NA Equity -> 2683 points
OK: NOKIA FH Equity -> 2633 points
OK: NOVN SW Equity -> 2633 points
OK: NOVOB DC Equity -> 2622 points
OK: NSISB DC Equity -> 2622 points
OK: NTGY SQ Equity -> 2681 points
OK: NWG LN Equity -> 2648 points
OK: NXT LN Equity -> 2648 points
OK: O2D GY Equity -> 2191 points
OK: OCDO LN Equity -> 2648 points
OK: OCI NA Equity -> 2683 points
OK: OERL SE Equity -> 2633 points
OK: OML LN Equity -> 711 points
OK: OMV AV Equity -> 2641 points
OK: ONTEX BB Equity -> 2682 points
OK: OPM FP Equity -> 2683 points
OK: OR FP Equity -> 2683 points
OK: ORA FP Equity -> 2683 points
OK: ORK NO Equity -> 2631 points
OK: ORNBV FH Equity -> 2633 points
OK: ORRON SS Equity -> 2633 points
OK: ORSTED DC Equity -> 2431 points
OK: OSR GY Equity -> 1473 points
OK: PAGE LN Equity -> 2648 points
OK: PAH3 GY Equity -> 2658 points
OK: PARG SE Equity -> 1314 points
OK: PAYS LN Equity -> 586 points
OK: PFC LN Equity -> 2422 points
OK: PGHN SW Equity -> 2633 points
OK: PHIA NA Equity -> 2683 points
OK: PHNX LN Equity -> 2648 points
OK: PMI IM Equity -> 341 points
OK: PNDORA DC Equity -> 2622 points
OK: PNL NA Equity -> 2683 points
OK: PNN LN Equity -> 2648 points
OK: POLY LN Equity -> 2000 points
OK: POP SQ Equity -> 455 points
OK: PROX BB Equity -> 2682 points
OK: PRU LN Equity -> 2648 points
OK: PRY IM Equity -> 2661 points
OK: PSM GY Equity -> 2658 points
OK: PSN LN Equity -> 2648 points
OK: PSON LN Equity -> 2648 points
OK: PSPN SE Equity -> 2633 points
OK: PST IM Equity -> 2622 points
OK: PTEC LN Equity -> 2648 points
OK: PUB FP Equity -> 2683 points
OK: QIA GY Equity -> 2658 points
OK: QQ/ LN Equity -> 2648 points
OK: RACE IM Equity -> 2576 points
OK: RAND NA Equity -> 2683 points
OK: RBI AV Equity -> 2641 points
OK: RDSA NA Equity -> 1644 points
OK: REC IM Equity -> 2661 points
OK: RED SQ Equity -> 2681 points
OK: REL LN Equity -> 2648 points
OK: RENT NA Equity -> 775 points
OK: REP SQ Equity -> 2681 points
OK: RF FP Equity -> 2683 points
OK: RGU LN Equity -> 331 points
OK: RHM GY Equity -> 2658 points
OK: RI FP Equity -> 2683 points
OK: RIO LN Equity -> 2648 points
OK: RKT LN Equity -> 2648 points
OK: RMS FP Equity -> 2683 points
OK: RMV LN Equity -> 2648 points
OK: RNO FP Equity -> 2683 points
OK: ROG SW Equity -> 2633 points
OK: ROR LN Equity -> 2648 points
OK: RPC LN Equity -> 968 points
OK: RR/ LN Equity -> 2648 points
OK: RRS LN Equity -> 844 points
OK: RRTL GY Equity -> 2658 points
OK: RSA LN Equity -> 1454 points
OK: RTO LN Equity -> 2648 points
OK: RUI FP Equity -> 2683 points
OK: RWE GY Equity -> 2658 points
OK: RXL FP Equity -> 2683 points
OK: RYA ID Equity -> 2667 points
OK: SAABB SS Equity -> 2633 points
OK: SAB LN Equity -> 279 points
OK: SAB SQ Equity -> 2681 points
OK: SAF FP Equity -> 2683 points
OK: SAGA LN Equity -> 2648 points
OK: SAMPO FH Equity -> 2633 points
OK: SAN FP Equity -> 2683 points
OK: SAN SQ Equity -> 2681 points
OK: SAND SS Equity -> 2633 points
OK: SAP GY Equity -> 2658 points
OK: SAZ GY Equity -> 823 points
OK: SBMO NA Equity -> 2683 points
OK: SBRY LN Equity -> 2648 points
OK: SCAB SS Equity -> 2633 points
OK: SCHP SW Equity -> 2633 points
OK: SCMN SW Equity -> 2633 points
OK: SCR FP Equity -> 2683 points
OK: SDF GY Equity -> 2658 points
OK: SDR LN Equity -> 2648 points
OK: SEBA SS Equity -> 2633 points
OK: SECUB SS Equity -> 2633 points
OK: SESG FP Equity -> 2683 points
OK: SEV FP Equity -> 1643 points
OK: SFR FP Equity -> 539 points
OK: SGE LN Equity -> 2648 points
OK: SGO FP Equity -> 2683 points
OK: SGRE SQ Equity -> 1910 points
OK: SGRO LN Equity -> 2648 points
OK: SGSN SW Equity -> 2633 points
OK: SHB LN Equity -> 1898 points
OK: SHBA SS Equity -> 2633 points
OK: SHC LN Equity -> 2648 points
OK: SHP LN Equity -> 848 points
OK: SIE GY Equity -> 2658 points
OK: SIG LN Equity -> 1454 points
OK: SIKA SW Equity -> 2633 points
OK: SK FP Equity -> 2683 points
OK: SKAB SS Equity -> 2633 points
OK: SKFB SS Equity -> 2633 points
OK: SKG ID Equity -> 2252 points
OK: SKY LN Equity -> 807 points
OK: SLHN SW Equity -> 2633 points
OK: SMDS LN Equity -> 2382 points
OK: SMIN LN Equity -> 2648 points
OK: SMWH LN Equity -> 2648 points
OK: SN/ LN Equity -> 2648 points
OK: SNH GY Equity -> 1617 points
OK: SOBI SS Equity -> 2633 points
OK: SOLB BB Equity -> 2683 points
OK: SOON SW Equity -> 2633 points
OK: SPM IM Equity -> 2661 points
OK: SPR GY Equity -> 1162 points
OK: SPSN SE Equity -> 2633 points
OK: SPX LN Equity -> 2648 points
OK: SRCG SE Equity -> 1404 points
OK: SREN SW Equity -> 2633 points
OK: SRG IM Equity -> 2661 points
OK: SRT3 GY Equity -> 2658 points
OK: SSE LN Equity -> 2648 points
OK: STAN LN Equity -> 2648 points
OK: STERV FH Equity -> 2633 points
OK: STJ LN Equity -> 2648 points
OK: STLAM IM Equity -> 2661 points
OK: STMMI IM Equity -> 2661 points
OK: STMN SE Equity -> 2633 points
OK: SU FP Equity -> 2683 points
OK: SUBC NO Equity -> 2631 points
OK: SVT LN Equity -> 2648 points
OK: SW FP Equity -> 2683 points
OK: SWEDA SS Equity -> 2633 points
OK: SWMA SS Equity -> 1847 points
OK: SXS LN Equity -> 2595 points
OK: SY1 GY Equity -> 2658 points
OK: SYNN SW Equity -> 593 points
OK: TALK LN Equity -> 1401 points
OK: TATE LN Equity -> 2648 points
OK: TDC DC Equity -> 691 points
OK: TEC FP Equity -> 355 points
OK: TEF SQ Equity -> 2681 points
OK: TEL NO Equity -> 2631 points
OK: TEL2B SS Equity -> 2633 points
OK: TELIA SS Equity -> 2633 points
OK: TEMN SE Equity -> 2633 points
OK: TEN IM Equity -> 2661 points
OK: TEP FP Equity -> 2683 points
OK: TIT IM Equity -> 2661 points
OK: TKA GY Equity -> 2658 points
OK: TL5 SQ Equity -> 1963 points
OK: TLW LN Equity -> 2648 points
OK: TNET BB Equity -> 2084 points
OK: TOP DC Equity -> 2289 points
OK: TPK LN Equity -> 2648 points
OK: TRELB SS Equity -> 2633 points
OK: TRN IM Equity -> 2661 points
OK: TRYG DC Equity -> 2622 points
OK: TSCO LN Equity -> 2648 points
OK: TTE FP Equity -> 2683 points
OK: TUI LN Equity -> 2225 points
OK: TW/ LN Equity -> 2648 points
OK: TYRES FH Equity -> 2633 points
OK: UBI FP Equity -> 2683 points
OK: UBI IM Equity -> 1292 points
OK: UBM LN Equity -> 706 points
OK: UBSG SW Equity -> 2633 points
OK: UCB BB Equity -> 2683 points
OK: UCG IM Equity -> 2661 points
OK: UG FP Equity -> 1376 points
OK: UHR SW Equity -> 2633 points
OK: UL NA Equity -> 706 points
OK: ULE LN Equity -> 1749 points
OK: ULVR LN Equity -> 2648 points
OK: UMI BB Equity -> 2683 points
OK: UN0 GY Equity -> 2396 points
OK: UPM FH Equity -> 2633 points
OK: US IM Equity -> 2248 points
OK: UTDI GY Equity -> 2658 points
OK: UU/ LN Equity -> 2648 points
OK: VANQ LN Equity -> 2648 points
OK: VANTI FP Equity -> 2680 points
OK: VCT LN Equity -> 2648 points
OK: VENDA NO Equity -> 2551 points
OK: VIE FP Equity -> 2683 points
OK: VIFN SW Equity -> 1843 points
OK: VIS SQ Equity -> 2681 points
OK: VIV FP Equity -> 2683 points
OK: VMUK LN Equity -> 2188 points
OK: VNA GY Equity -> 2658 points
OK: VOD LN Equity -> 2648 points
OK: VOE AV Equity -> 2641 points
OK: VOLVB SS Equity -> 2633 points
OK: VOW3 GY Equity -> 2658 points
OK: VPK NA Equity -> 2683 points
OK: VTY LN Equity -> 2648 points
OK: VWS DC Equity -> 2622 points
OK: WDI GY Equity -> 1352 points
OK: WEIR LN Equity -> 2648 points
OK: WG/ LN Equity -> 2517 points
OK: WHA NA Equity -> 2683 points
OK: WIE AV Equity -> 2641 points
OK: WKL NA Equity -> 2683 points
OK: WMH LN Equity -> 1428 points
OK: WPG LN Equity -> 572 points
OK: WPP LN Equity -> 2648 points
OK: WRT1V FH Equity -> 2633 points
OK: WTB LN Equity -> 2648 points
OK: YAR NO Equity -> 2631 points
OK: ZAL GY Equity -> 2658 points
OK: ZC FP Equity -> 653 points

WindowsPath('C:/Users/lenar25/Documents/Backtesting_M2272/data/initial_data/historical_price_memb_index.parquet')

In [ ]:
# visualsiation
stockage = ParquetStockage()

historical_price_memb_index = stockage.charger("historical_price_memb_index")

historical_price_memb_index.tail()

               Date           Ticker   Price
2281884  2026-02-16  VSURE SS Equity   9.899
2281885  2026-02-17  VSURE SS Equity  10.000
2281886  2026-02-18  VSURE SS Equity  10.014
2281887  2026-02-19  VSURE SS Equity   9.804
2281888  2026-02-20  VSURE SS Equity   9.752

Data Management


## 6. Data MAnagement des prix historiques <a id='1'></a>

**Objectif** : obtenir quelques chose de compatibles pour backtester

In [8]:
from request.utils import DataManagement  

dm = DataManagement()

df_wide = dm.format_historical_price(historical_price_memb_index)

df_wide.tail()

Ticker,Date,1844030D NA Equity,1986986D LN Equity,1CNHI IM Equity,1COV GY Equity,1U1 GY Equity,2261689D LN Equity,2462936D LN Equity,2578464D GY Equity,2627525D LN Equity,...,WTB LN Equity,YAR NO Equity,ZAL GY Equity,ZC FP Equity,ZEAL DC Equity,ZEG LN Equity,ZO1 GY Equity,ZOT SQ Equity,ZURN SE Equity,ZURN SW Equity
2685,2026-02-16,NaN,NaN,10.52,NaN,24.60,NaN,NaN,NaN,NaN,...,2691.0,446.0,21.14,NaN,390.1,1640.0,NaN,NaN,557.6,557.6
2686,2026-02-17,NaN,NaN,11.02,NaN,24.45,NaN,NaN,NaN,NaN,...,2738.0,445.0,21.56,NaN,388.0,1695.0,NaN,NaN,564.0,564.0
2687,2026-02-18,NaN,NaN,10.64,NaN,24.15,NaN,NaN,NaN,NaN,...,2757.0,454.3,21.16,NaN,396.4,1785.0,NaN,NaN,568.0,568.0
2688,2026-02-19,NaN,NaN,11.06,NaN,23.55,NaN,NaN,NaN,NaN,...,2737.0,460.0,21.03,NaN,382.8,1790.0,NaN,NaN,558.8,558.8
2689,2026-02-20,NaN,NaN,10.94,NaN,22.55,NaN,NaN,NaN,NaN,...,2730.0,467.8,20.69,NaN,392.9,1815.0,NaN,NaN,567.8,567.8

verification


## 7. Vérification finale <a id='1'></a>

In [ ]:
# benchmark / taux sans risque pour portefeuille long/short
estron_index_px_last = stockage.charger("ESTRON Index_PX_LAST")
estron_index_px_last.tail()

            Date  ESTRON Index
1633  2026-02-16         1.929
1634  2026-02-17         1.931
1635  2026-02-18         1.931
1636  2026-02-19         1.933
1637  2026-02-20         1.932

In [ ]:
# Benchmark indice univers
stockage = ParquetStockage()

sxxp_index_px_last = stockage.charger("SXXP Index_PX_LAST")

sxxp_index_px_last.tail()

            Date  SXXP Index
2427  2026-02-16      618.52
2428  2026-02-17      621.29
2429  2026-02-18      628.69
2430  2026-02-19      625.33
2431  2026-02-20      630.56

In [ ]:
# Composants membre indice univers
stockage = ParquetStockage()

index_memb_20260220 = stockage.charger("index_memb_20260220")

index_memb_20260220.tail()

           Date   Ticker
595  1970-01-01   YAR NO
596  1970-01-01   ZAL GY
597  1970-01-01  ZEAL DC
598  1970-01-01   ZEG LN
599  1970-01-01  ZURN SE

In [ ]:
# membres historiques de l'indice univers
stockage = ParquetStockage()

historical_index_memb = stockage.charger("historical_index_memb")

historical_index_memb.tail()

             Date   Ticker
68397  1970-01-01   YAR NO
68398  1970-01-01   ZAL GY
68399  1970-01-01  ZEAL DC
68400  1970-01-01   ZEG LN
68401  1970-01-01  ZURN SE

In [ ]:
# Historiques des informations sur les membres historiques
stockage = ParquetStockage()

informations_hist_memb_index = stockage.charger("informations_hist_memb_index")

informations_hist_memb_index.tail()

,Ticker,Name,Currency,Sector,Industry,Country
975,ABVX FP Equity,ABIVAX SA,EUR,Soins de santé,Biotechnologie,FRANCE
976,AMV0 GY Equity,AUMOVIO SE,EUR,Consommation discrétionnaire,Composants automobiles,GERMANY
977,CAMX SS Equity,CAMURUS AB,SEK,Soins de santé,Produits pharmaceutiques,SWEDEN
978,FTK GY Equity,FLATEXDEGIRO SE,EUR,Finance,Marchés de capitaux,GERMANY
979,NDX1 GY Equity,NORDEX SE,EUR,Industrie,Matériel électrique,GERMANY

In [ ]:
# Historique de prix des membres de l'indice univers
stockage = ParquetStockage()

historical_price_memb_index = stockage.charger("historical_price_memb_index")

historical_price_memb_index.tail()

               Date           Ticker   Price
2281884  2026-02-16  VSURE SS Equity   9.899
2281885  2026-02-17  VSURE SS Equity  10.000
2281886  2026-02-18  VSURE SS Equity  10.014
2281887  2026-02-19  VSURE SS Equity   9.804
2281888  2026-02-20  VSURE SS Equity   9.752

In [17]:
from request.utils import DataManagement  

dm = DataManagement()

df_wide = dm.format_historical_price(historical_price_memb_index)

df_wide.tail()

Ticker,Date,1844030D NA Equity,1986986D LN Equity,1CNHI IM Equity,1COV GY Equity,1U1 GY Equity,2261689D LN Equity,2462936D LN Equity,2578464D GY Equity,2627525D LN Equity,...,WTB LN Equity,YAR NO Equity,ZAL GY Equity,ZC FP Equity,ZEAL DC Equity,ZEG LN Equity,ZO1 GY Equity,ZOT SQ Equity,ZURN SE Equity,ZURN SW Equity
2685,2026-02-16,NaN,NaN,10.52,NaN,24.60,NaN,NaN,NaN,NaN,...,2691.0,446.0,21.14,NaN,390.1,1640.0,NaN,NaN,557.6,557.6
2686,2026-02-17,NaN,NaN,11.02,NaN,24.45,NaN,NaN,NaN,NaN,...,2738.0,445.0,21.56,NaN,388.0,1695.0,NaN,NaN,564.0,564.0
2687,2026-02-18,NaN,NaN,10.64,NaN,24.15,NaN,NaN,NaN,NaN,...,2757.0,454.3,21.16,NaN,396.4,1785.0,NaN,NaN,568.0,568.0
2688,2026-02-19,NaN,NaN,11.06,NaN,23.55,NaN,NaN,NaN,NaN,...,2737.0,460.0,21.03,NaN,382.8,1790.0,NaN,NaN,558.8,558.8
2689,2026-02-20,NaN,NaN,10.94,NaN,22.55,NaN,NaN,NaN,NaN,...,2730.0,467.8,20.69,NaN,392.9,1815.0,NaN,NaN,567.8,567.8